
const e=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
(async()=>{const {data:{user}}=await supabaseClient.auth.getUser();if(!user){ceoAccess.innerHTML='Please <a href="admin.html">sign in</a> first.';return}const {data:p}=await supabaseClient.from('admin_users').select('*').eq('user_id',user.id).single();if(!p||!['CEO','Super Admin'].includes(p.role)){ceoAccess.textContent='CEO access required.';return}ceoAccess.classList.add('hidden');ceoWorkspace.classList.remove('hidden');await loadCEO()})();
async function loadCEO(){
 const [snap,att,sec,reps,onl,acts]=await Promise.all([supabaseClient.from('department_operations_snapshot').select('*').order('department_name'),supabaseClient.rpc('company_attendance_today'),supabaseClient.from('security_incidents').select('*').order('created_at',{ascending:false}).limit(50),supabaseClient.from('management_reports').select('*,departments(name)').order('created_at',{ascending:false}).limit(50),supabaseClient.rpc('ceo_online_staff'),supabaseClient.from('staff_activity_logs').select('*').order('created_at',{ascending:false}).limit(30)]);
 const d=snap.data||[],a=att.data||[],s=sec.data||[],r=reps.data||[],o=onl.data||[],ac=acts.data||[];
 ceoStats.innerHTML=[['Departments',d.length],['Present',a.filter(x=>['On Time','Late','Working'].includes(x.status)).length],['On Break',a.filter(x=>x.work_status==='On Break').length],['Field Duty',a.filter(x=>x.work_status==='Field Duty').length],['Urgent Work',d.reduce((n,x)=>n+Number(x.urgent_work||0),0)],['Critical Security',s.filter(x=>x.severity==='Critical'&&x.status!=='Closed').length]].map(x=>`<div class="neb-stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
 ceoDepartments.innerHTML=d.map(x=>`<div class="neb-row"><strong>${e(x.department_name)}</strong><p>HOD: ${e(x.hod_name||'Not assigned')} · Staff ${x.active_staff||0} · Open ${x.open_work||0} · Urgent ${x.urgent_work||0} · On Break ${x.on_break||0}</p></div>`).join('')||'<p>No department data.</p>';
 ceoAttendance.innerHTML=a.map(x=>`<div class="neb-row"><strong>${e(x.full_name)}</strong><p>${e(x.department)} · Attendance: ${e(x.status)} · Current: ${e(x.work_status||'—')}</p></div>`).join('')||'<p>No attendance records.</p>';
 ceoSecurity.innerHTML=s.map(x=>`<div class="neb-row"><div class="neb-row-head"><strong>${e(x.incident_number)} — ${e(x.title)}</strong><span class="neb-tag ${x.severity==='Critical'?'red':'orange'}">${e(x.severity)}</span></div><p>${e(x.summary||'')}<br><b>System action:</b> ${e(x.system_action||'Logged')}<br><b>Recommended:</b> ${e(x.recommended_action||'Review evidence and determine next action.')}</p><button onclick="securityAction('${x.id}')">CEO Review</button></div>`).join('')||'<p>No security incidents.</p>';
 ceoReports.innerHTML=r.map(x=>`<div class="neb-row"><strong>${e(x.title)}</strong><p>${e(x.departments?.name||'')} · ${e(x.report_type)} · ${e(x.status)}<br>${e(x.summary||'')}</p></div>`).join('')||'<p>No management reports.</p>';
 ceoOnline.innerHTML=o.map(x=>`<div class="neb-row"><strong>${e(x.full_name)}</strong><p>${e(x.role)} · ${e(x.current_page||'System')} · ${new Date(x.last_seen_at).toLocaleString()}</p></div>`).join('')||'<p>No staff currently online.</p>';
 ceoActivity.innerHTML=ac.map(x=>`<div class="neb-row"><strong>${e(x.action)}</strong><p>${e(x.page||'')} · ${new Date(x.created_at).toLocaleString()}</p></div>`).join('')||'<p>No recent activity.</p>';
}
window.securityAction=async id=>{const action=prompt('CEO action / decision:','Review and investigate');if(!action)return;const {error}=await supabaseClient.rpc('ceo_record_security_action',{p_incident_id:id,p_action:action});if(error)alert(error.message);else loadCEO()};
