let activities=[];const access=document.getElementById('ceoAccess'),workspace=document.getElementById('ceoWorkspace');
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function fmt(v){return v?new Date(v).toLocaleString():'—';}
async function init(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user){access.innerHTML='Please <a href="admin.html">log in</a> first.';return;}const {data:p,error}=await supabaseClient.from('admin_users').select('*').eq('user_id',user.id).single();if(error||!p||!['CEO','Super Admin'].includes(p.role)){access.textContent='CEO or Super Admin access is required.';return;}access.classList.add('hidden');workspace.classList.remove('hidden');await supabaseClient.rpc('record_staff_login',{p_page:'ceo'});await refreshAll();}
async function refreshAll(){await Promise.all([loadAttendance(),loadOnline(),loadActivities()]);}
async function loadAttendance(){const {data,error}=await supabaseClient.rpc('ceo_attendance_today');if(error){document.getElementById('attendanceRanking').textContent=error.message;return;}const rows=data||[];document.getElementById('expectedCount').textContent=rows.length;document.getElementById('presentCount').textContent=rows.filter(r=>['On Time','Late'].includes(r.status)).length;document.getElementById('lateCount').textContent=rows.filter(r=>r.status==='Late').length;document.getElementById('absentCount').textContent=rows.filter(r=>r.status==='Not Arrived').length;document.getElementById('attendanceRanking').innerHTML=rows.map((r,i)=>`<div class="attendance-ranking-row"><span class="rank-number">${i+1}</span><div><strong>${esc(r.full_name)}</strong><small>${esc(r.role)} · ${esc(r.department)}</small></div><span>${r.check_in_at?new Date(r.check_in_at).toLocaleTimeString():'—'}</span><span class="attendance-badge ${String(r.status).toLowerCase().replaceAll(' ','-')}">${esc(r.status)}</span></div>`).join('')||'<p>No active staff found.</p>';}
async function loadOnline(){const {data,error}=await supabaseClient.rpc('ceo_online_staff');if(error)return;document.getElementById('onlineCount').textContent=(data||[]).length;document.getElementById('onlineStaff').innerHTML=(data||[]).map(r=>`<div class="online-row"><span class="online-dot"></span><div><strong>${esc(r.full_name)}</strong><small>${esc(r.role)} · ${esc(r.current_page||'System')}</small></div><span>${fmt(r.last_seen_at)}</span></div>`).join('')||'<p>No staff currently online.</p>';}
async function loadActivities(){const days=Number(document.getElementById('activityPeriod').value||1);const since=new Date(Date.now()-days*86400000).toISOString();const {data,error}=await supabaseClient.from('staff_activity_logs').select('*,admin_users!staff_activity_logs_user_id_fkey(full_name,role,department)').gte('created_at',since).order('created_at',{ascending:false}).limit(500);if(error){document.getElementById('activityBody').innerHTML=`<tr><td colspan="6">${esc(error.message)}</td></tr>`;return;}activities=data||[];renderActivities();}
function renderActivities(){const q=document.getElementById('activitySearch').value.toLowerCase();const rows=activities.filter(r=>`${r.admin_users?.full_name||''} ${r.admin_users?.role||''} ${r.action} ${r.page||''}`.toLowerCase().includes(q));document.getElementById('activityBody').innerHTML=rows.map(r=>`<tr><td>${fmt(r.created_at)}</td><td>${esc(r.admin_users?.full_name||'Staff')}</td><td>${esc(r.admin_users?.role||'')}</td><td>${esc(r.admin_users?.department||'')}</td><td>${esc(r.action)}</td><td>${esc(r.page||'')}</td></tr>`).join('')||'<tr><td colspan="6">No activity found.</td></tr>';}
document.getElementById('refreshCeo').addEventListener('click',refreshAll);document.getElementById('activityPeriod').addEventListener('change',loadActivities);document.getElementById('activitySearch').addEventListener('input',renderActivities);init();