
window.NEBCTRL={};
NEBCTRL.security=async()=>{
 const host=document.getElementById('modMain');if(!host)return;
 const [cam,inc,pat]=await Promise.all([supabaseClient.from('security_cameras').select('*').order('camera_code'),supabaseClient.from('security_incidents').select('*').order('created_at',{ascending:false}).limit(30),supabaseClient.from('security_patrols').select('*').order('created_at',{ascending:false}).limit(30)]);
 const c=cam.data||[],i=inc.data||[],p=pat.data||[];
 host.innerHTML=`<section class="neb-card"><div class="neb-section-title"><h2>Security Command Wall</h2><button class="btn btn-primary" onclick="NEBCTRL.newIncident()">Report Incident</button></div><div class="neb-control-wall"><div class="neb-monitor"><span>CCTV</span><strong>${c.filter(x=>x.status==='Online').length}/${c.length} ONLINE</strong><span class="${c.some(x=>x.status!=='Online')?'warning':'online'}">${c.some(x=>x.status!=='Online')?'Attention required':'Recording healthy'}</span></div><div class="neb-monitor"><span>Active Incidents</span><strong>${i.filter(x=>x.status!=='Closed').length}</strong><span class="${i.some(x=>x.severity==='Critical'&&x.status!=='Closed')?'critical':'online'}">Incident command</span></div><div class="neb-monitor"><span>Patrols</span><strong>${p.filter(x=>x.status==='In Progress').length}</strong><span class="online">Live duty status</span></div><div class="neb-monitor"><span>Security State</span><strong>${i.some(x=>x.severity==='Critical'&&x.status!=='Closed')?'CRITICAL':'NORMAL'}</strong><span class="${i.some(x=>x.severity==='Critical'&&x.status!=='Closed')?'critical':'online'}">Risk monitoring</span></div></div></section>
 <div class="neb-grid-2"><article class="neb-card"><h2>CCTV Cameras</h2>${c.map(x=>`<div class="neb-row"><strong>${NEBUI.escape(x.camera_code)} — ${NEBUI.escape(x.location)}</strong><p>Status ${NEBUI.escape(x.status)} · Recording ${x.recording?'ON':'OFF'} · NVR ${NEBUI.escape(x.nvr_name||'—')}</p></div>`).join('')||'<p>No cameras registered. Add real camera/NVR integrations after hardware details are available.</p>'}</article><article class="neb-card"><h2>Incidents & Emergency</h2>${i.map(x=>`<div class="neb-row"><strong>${NEBUI.escape(x.incident_number)} — ${NEBUI.escape(x.title)}</strong><p>${NEBUI.escape(x.severity)} · ${NEBUI.escape(x.status)} · ${NEBUI.escape(x.location||'')}</p></div>`).join('')||'<p>No active security incidents.</p>'}</article><article class="neb-card"><h2>Guard Posts & Patrols</h2><p>Shifts, posts, patrol routes, checkpoints and handover records.</p>${p.map(x=>`<div class="neb-row"><strong>${NEBUI.escape(x.patrol_number)}</strong><p>${NEBUI.escape(x.route_name)} · ${NEBUI.escape(x.status)}</p></div>`).join('')||'<p>No patrol records.</p>'}</article><article class="neb-card"><h2>Access & Risk Register</h2><p>Visitor access, restricted areas, vehicle/gate control, risk mitigation and confidential investigations.</p></article></div>`;
};
NEBCTRL.newIncident=()=>NEBUI.modal({title:'Report Security Incident',fields:[{name:'type',label:'Incident type',type:'select',options:['Suspicious Activity','Unauthorized Access','Theft / Loss','Property Damage','CCTV / Alarm','Visitor Incident','Vehicle / Gate','Emergency','Other']},{name:'severity',label:'Severity',type:'select',options:['Low','Medium','High','Critical']},{name:'location',label:'Location',required:true},{name:'title',label:'Incident title',required:true,full:true},{name:'summary',label:'What happened?',type:'textarea',required:true,full:true}],submitText:'Create Incident',onSubmit:async v=>{const {data,error}=await supabaseClient.rpc('security_report_incident',{p_title:v.title,p_summary:v.summary,p_incident_type:v.type,p_severity:v.severity,p_location:v.location});if(error)throw error;NEBUI.toast(`Incident ${data} created.`,'success');setTimeout(NEBCTRL.security,100);return true}});
NEBCTRL.it=async()=>{
 const host=document.getElementById('modMain');if(!host)return;
 const [systems,tickets,backs,cams]=await Promise.all([supabaseClient.from('it_systems').select('*').order('name'),supabaseClient.from('it_tickets').select('*').order('created_at',{ascending:false}).limit(40),supabaseClient.from('it_backups').select('*').order('created_at',{ascending:false}).limit(10),supabaseClient.from('security_cameras').select('*').order('camera_code')]);
 const s=systems.data||[],t=tickets.data||[],b=backs.data||[],c=cams.data||[];
 host.innerHTML=`<section class="neb-card"><div class="neb-section-title"><h2>NEBRIN Central System & Security Control Centre</h2><button class="btn btn-primary" onclick="NEBRIN.askAI()">AI Diagnose / Ticket</button></div><div class="neb-control-wall"><div class="neb-monitor"><span>Systems</span><strong>${s.filter(x=>x.status==='Operational').length}/${s.length} HEALTHY</strong><span class="online">Infrastructure</span></div><div class="neb-monitor"><span>IT Tickets</span><strong>${t.filter(x=>!['Resolved','Closed'].includes(x.status)).length} OPEN</strong><span class="warning">Help desk</span></div><div class="neb-monitor"><span>Backup</span><strong>${b[0]?.status||'NO RECORD'}</strong><span class="${b[0]?.status==='Successful'?'online':'warning'}">${b[0]?.created_at?new Date(b[0].created_at).toLocaleString():'Verification required'}</span></div><div class="neb-monitor"><span>CCTV Technical Health</span><strong>${c.filter(x=>x.status==='Online').length}/${c.length}</strong><span class="${c.some(x=>x.status!=='Online')?'warning':'online'}">IT + Security shared</span></div></div></section>
 <div class="neb-grid-2"><article class="neb-card"><h2>Systems & Website Monitoring</h2>${s.map(x=>`<div class="neb-row"><strong>${NEBUI.escape(x.name)}</strong><p>${NEBUI.escape(x.system_type)} · ${NEBUI.escape(x.status)} · Last check ${x.last_checked_at?new Date(x.last_checked_at).toLocaleString():'—'}</p></div>`).join('')||'<p>Register production systems, domains, database, email and integrations.</p>'}</article><article class="neb-card"><h2>Help Desk Queue</h2>${t.map(x=>`<div class="neb-row"><strong>${NEBUI.escape(x.ticket_number)} — ${NEBUI.escape(x.title)}</strong><p>${NEBUI.escape(x.category)} · ${NEBUI.escape(x.priority)} · ${NEBUI.escape(x.status)}</p></div>`).join('')||'<p>No tickets.</p>'}</article><article class="neb-card"><h2>Cybersecurity & Access Control</h2><p>Failed logins, suspicious access, account locks, privileged access requests and security incidents are monitored here.</p></article><article class="neb-card"><h2>Assets, Backup & Recovery</h2><p>Asset register, warranty/licence expiry, maintenance, backup verification and restore tests.</p></article></div>`;
};
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{const m=document.body.dataset.module;if(m==='security')NEBCTRL.security();if(m==='it')NEBCTRL.it()},420));
