
window.NEBFIN={};
NEBFIN.load=async()=>{
 const host=document.getElementById('modMain');if(!host)return;
 const panel=document.createElement('section');panel.className='neb-card';panel.innerHTML=`<div class="neb-section-title"><h2>Accounting Books & Financial Statements</h2><div class="neb-module-toolbar"><button onclick="NEBFIN.newJournal()">New Journal Entry</button><button onclick="NEBFIN.showLedger()">General Ledger</button><button onclick="NEBFIN.showTrial()">Trial Balance</button><button onclick="NEBFIN.showIncome()">Income & Expenditure</button><button class="btn btn-primary" onclick="NEBFIN.generateReport()">Generate Financial Report</button></div></div><div id="financeBookView"><p>Select an accounting book above. All posted journals must balance Debit = Credit.</p></div>`;
 host.prepend(panel);await NEBFIN.showDaily();
};
NEBFIN.newJournal=()=>NEBUI.modal({title:'Post Journal Entry',subtitle:'Double-entry accounting — total debit must equal total credit',fields:[
{name:'date',label:'Transaction date',type:'date',required:true},{name:'reference',label:'Reference / voucher no.'},{name:'description',label:'Narration / description',full:true,required:true},
{name:'debit_account',label:'Debit account',required:true},{name:'debit',label:'Debit amount (TZS)',type:'number',required:true},
{name:'credit_account',label:'Credit account',required:true},{name:'credit',label:'Credit amount (TZS)',type:'number',required:true}],submitText:'Post Journal',onSubmit:async v=>{if(Number(v.debit)!==Number(v.credit))throw new Error('Debit and Credit must be equal.');const {data,error}=await supabaseClient.rpc('finance_post_simple_journal',{p_entry_date:v.date,p_reference:v.reference,p_description:v.description,p_debit_account:v.debit_account,p_credit_account:v.credit_account,p_amount:v.debit});if(error)throw error;NEBUI.toast(`Journal ${data} posted.`,'success');await NEBFIN.showLedger();return true}});
NEBFIN.showDaily=async()=>{const {data,error}=await supabaseClient.from('finance_transactions').select('*').order('created_at',{ascending:false}).limit(50);financeBookView.innerHTML=error?NEBUI.escape(error.message):`<h3>Daily Transactions</h3><div class="neb-table-wrap"><table class="neb-ledger-table"><tr><th>Date</th><th>Type</th><th>Reference</th><th>Description</th><th>Amount</th></tr>${(data||[]).map(x=>`<tr><td>${new Date(x.created_at).toLocaleDateString()}</td><td>${NEBUI.escape(x.transaction_type)}</td><td>${NEBUI.escape(x.reference||'')}</td><td>${NEBUI.escape(x.description||'')}</td><td>${NEBRIN.money(x.amount)}</td></tr>`).join('')}</table></div>`};
NEBFIN.showLedger=async()=>{const {data,error}=await supabaseClient.from('finance_ledger_view').select('*').order('entry_date',{ascending:false}).limit(300);financeBookView.innerHTML=error?NEBUI.escape(error.message):`<h3>General Ledger</h3><div class="neb-table-wrap"><table class="neb-ledger-table"><tr><th>Date</th><th>Journal</th><th>Account</th><th>Description</th><th>Debit</th><th>Credit</th></tr>${(data||[]).map(x=>`<tr><td>${NEBUI.escape(x.entry_date)}</td><td>${NEBUI.escape(x.journal_number)}</td><td>${NEBUI.escape(x.account_name)}</td><td>${NEBUI.escape(x.description)}</td><td>${NEBRIN.money(x.debit)}</td><td>${NEBRIN.money(x.credit)}</td></tr>`).join('')}</table></div>`};
NEBFIN.showTrial=async()=>{const {data,error}=await supabaseClient.from('finance_trial_balance').select('*').order('account_name');financeBookView.innerHTML=error?NEBUI.escape(error.message):`<h3>Trial Balance</h3><div class="neb-table-wrap"><table class="neb-ledger-table"><tr><th>Account</th><th>Debit</th><th>Credit</th><th>Balance</th></tr>${(data||[]).map(x=>`<tr><td>${NEBUI.escape(x.account_name)}</td><td>${NEBRIN.money(x.total_debit)}</td><td>${NEBRIN.money(x.total_credit)}</td><td>${NEBRIN.money(x.balance)}</td></tr>`).join('')}</table></div>`};
NEBFIN.showIncome=async()=>{const {data,error}=await supabaseClient.rpc('finance_income_expenditure_summary');const x=Array.isArray(data)?data[0]:data;financeBookView.innerHTML=error?NEBUI.escape(error.message):`<h3>Income & Expenditure</h3><div class="neb-pro-kpis"><div class="neb-pro-kpi"><span>Total Income</span><strong>${NEBRIN.money(x?.income||0)}</strong></div><div class="neb-pro-kpi"><span>Total Expenditure</span><strong>${NEBRIN.money(x?.expenditure||0)}</strong></div><div class="neb-pro-kpi"><span>Net Result</span><strong>${NEBRIN.money(x?.net_result||0)}</strong></div></div>`};
NEBFIN.generateReport=()=>NEBUI.modal({title:'Generate Financial Report',subtitle:'Figures are generated from accounting records; AI may draft the narrative only.',fields:[{name:'period',label:'Period',type:'select',options:['Daily','Weekly','Monthly','Quarterly','Annual']},{name:'from',label:'From',type:'date'},{name:'to',label:'To',type:'date'},{name:'title',label:'Report title',value:'Financial Report',full:true}],submitText:'Generate & Send to Management',onSubmit:async v=>{const {data,error}=await supabaseClient.rpc('finance_generate_management_report',{p_title:v.title,p_period:v.period,p_from:v.from||null,p_to:v.to||null});if(error)throw error;NEBUI.toast(`Financial report ${data} generated and sent to Management.`,'success');return true}});
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.body.dataset.module==='finance')NEBFIN.load()},350));
