
const e=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
(async()=>{const {data:{user}}=await supabaseClient.auth.getUser();if(!user){mgrAccess.innerHTML='Please <a href="admin.html">sign in</a> first.';return}const {data:p}=await supabaseClient.from('admin_users').select('*').eq('user_id',user.id).single();if(!p||!['CEO','Super Admin','Manager'].includes(p.role)){mgrAccess.textContent='Manager access required.';return}mgrAccess.classList.add('hidden');mgrWorkspace.classList.remove('hidden');loadManager()})();
async function loadManager(){
 const [d,h,s,r]=await Promise.all([supabaseClient.from('department_operations_snapshot').select('*').order('department_name'),supabaseClient.from('department_leadership_view').select('*').order('department_name'),supabaseClient.from('admin_users').select('*').eq('approval_status','Pending').order('created_at',{ascending:false}),supabaseClient.from('management_reports').select('*,departments(name)').eq('status','Submitted').order('created_at',{ascending:false})]);
 const ds=d.data||[],hs=h.data||[],ss=s.data||[],rs=r.data||[];
 mgrStats.innerHTML=[['Departments',ds.length],['Open Work',ds.reduce((n,x)=>n+Number(x.open_work||0),0)],['Urgent',ds.reduce((n,x)=>n+Number(x.urgent_work||0),0)],['Pending Staff',ss.length],['HOD Missing',hs.filter(x=>!x.hod_user_id).length],['Reports',rs.length]].map(x=>`<div class="neb-stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
 mgrDepartments.innerHTML=ds.map(x=>`<div class="neb-row"><strong>${e(x.department_name)}</strong><p>HOD ${e(x.hod_name||'Not assigned')} · Staff ${x.active_staff||0} · Open ${x.open_work||0} · Urgent ${x.urgent_work||0} · Overdue ${x.overdue_work||0}</p></div>`).join('');
 mgrHods.innerHTML=hs.map(x=>`<div class="neb-row"><strong>${e(x.department_name)}</strong><p>HOD: ${e(x.hod_name||'Not assigned')} · Deputy: ${e(x.deputy_name||'Not assigned')}</p><button onclick="assignHod('${x.department_id}')">Assign / Change HOD</button></div>`).join('');
 mgrStaff.innerHTML=ss.map(x=>`<div class="neb-row"><strong>${e(x.full_name||x.email)}</strong><p>${e(x.role)} · ${e(x.department)}</p><button onclick="decideStaff('${x.user_id}','Approved')">Approve</button> <button onclick="decideStaff('${x.user_id}','Rejected')">Reject</button></div>`).join('')||'<p>No pending staff.</p>';
 mgrReports.innerHTML=rs.map(x=>`<div class="neb-row"><strong>${e(x.title)}</strong><p>${e(x.departments?.name||'')} · ${e(x.report_type)}<br>${e(x.summary||'')}</p></div>`).join('')||'<p>No submitted reports.</p>';
}
window.assignHod=async dept=>{const {data:staff}=await supabaseClient.from('admin_users').select('user_id,full_name,role,department').eq('approval_status','Approved').eq('is_active',true).order('full_name');const list=(staff||[]).map((x,i)=>`${i+1}. ${x.full_name} — ${x.role} / ${x.department}`).join('\n');const n=Number(prompt('Choose HOD:\n'+list));if(!n||!staff[n-1])return;const {error}=await supabaseClient.rpc('assign_department_hod',{p_department_id:dept,p_hod_user_id:staff[n-1].user_id});if(error)alert(error.message);else loadManager()};
window.decideStaff=async(id,d)=>{const {error}=await supabaseClient.rpc('management_decide_staff',{p_user_id:id,p_decision:d,p_reason:'Manager dashboard decision'});if(error)alert(error.message);else loadManager()};
