const access=document.getElementById('managerAccess'),workspace=document.getElementById('managerWorkspace');let staff=[];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function init(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user){access.innerHTML='Please <a href="admin.html">sign in</a> first.';return;}const {data:p,error}=await supabaseClient.from('admin_users').select('*').eq('user_id',user.id).single();if(error||!p||!['CEO','Super Admin','Manager'].includes(p.role)||p.approval_status!=='Approved'){access.textContent='Approved Manager access is required.';return;}access.classList.add('hidden');workspace.classList.remove('hidden');await supabaseClient.rpc('record_staff_login',{p_page:'manager'});await refresh();}
async function refresh(){await Promise.all([loadStaff(),loadPending(),loadApps()]);}
async function loadStaff(){const {data}=await supabaseClient.from('admin_users').select('*').eq('approval_status','Approved').eq('is_active',true).order('full_name');staff=data||[];}
async function loadPending(){const {data,error}=await supabaseClient.from('admin_users').select('*').eq('approval_status','Pending').order('created_at',{ascending:false});if(error){document.getElementById('managerPendingList').textContent=error.message;return;}document.getElementById('managerPendingStaff').textContent=(data||[]).length;document.getElementById('managerPendingList').innerHTML=(data||[]).map(s=>`<div class="reference-result-card"><strong>${esc(s.full_name||s.email||'Pending staff')}</strong><p>${esc(s.role)} · ${esc(s.department)} · ${esc(s.email||'')}</p><div class="reference-result-actions"><button onclick="approveStaff('${s.user_id}')">Approve</button><button onclick="rejectStaff('${s.user_id}')">Reject</button></div></div>`).join('')||'<p>No pending approvals.</p>';}
window.approveStaff=async id=>{const {error}=await supabaseClient.rpc('management_decide_staff',{p_user_id:id,p_decision:'Approved',p_reason:''});if(error)alert(error.message);else refresh();};
window.rejectStaff=async id=>{const reason=prompt('Reason for rejection:')||'';const {error}=await supabaseClient.rpc('management_decide_staff',{p_user_id:id,p_decision:'Rejected',p_reason:reason});if(error)alert(error.message);else refresh();};
async function loadApps(){const {data,error}=await supabaseClient.from('applications').select('*').is('deleted_at',null).order('created_at',{ascending:false});if(error){document.getElementById('managerApplications').textContent=error.message;return;}const rows=data||[];document.getElementById('managerUnassigned').textContent=rows.filter(a=>!a.assigned_to).length;document.getElementById('managerProcessing').textContent=rows.filter(a=>a.status==='Processing').length;const today=new Date().toDateString();document.getElementById('managerCompleted').textContent=rows.filter(a=>a.status==='Completed'&&new Date(a.completed_at||a.created_at).toDateString()===today).length;const by={};rows.forEach(a=>{const d=a.department||'Unassigned';by[d]=(by[d]||0)+1});document.getElementById('managerDepartmentLoad').innerHTML=Object.entries(by).map(([d,n])=>`<div class="online-row"><strong>${esc(d)}</strong><span>${n}</span></div>`).join('');document.getElementById('managerApplications').innerHTML=rows.filter(a=>!a.assigned_to).map(a=>`<div class="reference-result-card"><strong>${esc(a.reference)} — ${esc(a.service)}</strong><p>${esc(a.full_name)} · ${esc(a.phone)}</p><div class="reference-result-actions"><button onclick="assign('${a.id}')">Assign Staff</button></div></div>`).join('')||'<p>No unassigned applications.</p>';}
window.assign=async id=>{const options=staff.map((s,i)=>`${i+1}. ${s.full_name} — ${s.role}/${s.department}`).join('\n');const n=Number(prompt(`Choose staff number:\n${options}`));const s=staff[n-1];if(!s)return;const {error}=await supabaseClient.from('applications').update({assigned_to:s.user_id,department:s.department}).eq('id',id);if(error)alert(error.message);else loadApps();};init();