
window.NEBREG={};
NEBREG.load=async()=>{
 const host=document.getElementById('modMain');if(!host)return;
 const {data,error}=await supabaseClient.from('registry_records').select('*').order('received_at',{ascending:false}).limit(100);
 const r=data||[];host.innerHTML=`<section class="neb-card"><div class="neb-section-title"><h2>Registry Control Desk</h2><button class="btn btn-primary" onclick="NEBREG.newRecord()">Register Document</button></div><div class="neb-doc-class-grid"><div class="neb-doc-class"><strong>Office / Internal</strong><p>${r.filter(x=>x.owner_type==='Office').length} records</p></div><div class="neb-doc-class"><strong>Customer / Client</strong><p>${r.filter(x=>x.owner_type==='Customer').length} records</p></div><div class="neb-doc-class"><strong>Visitor / External</strong><p>${r.filter(x=>x.owner_type==='External').length} records</p></div><div class="neb-doc-class"><strong>Confidential / Restricted</strong><p>${r.filter(x=>/Confidential|Restricted|Executive/i.test(x.classification||'')).length} records</p></div></div></section>
 <div class="neb-grid-2"><article class="neb-card"><h2>Incoming / Outgoing Registry</h2>${r.map(x=>`<div class="neb-row"><strong>${NEBUI.escape(x.file_number)} — ${NEBUI.escape(x.subject)}</strong><p>${NEBUI.escape(x.owner_type||'Office')} · ${NEBUI.escape(x.record_type||'Record')} · ${NEBUI.escape(x.classification||'Internal')} · ${NEBUI.escape(x.status)}</p></div>`).join('')||'<p>No registry records.</p>'}</article><article class="neb-card"><h2>Archives & File Movement</h2><p>Track active, on-reference, physical shelf/box location, returned files, retention review and authorized disposal.</p></article><article class="neb-card"><h2>Library & Publications</h2><p>Books, journals, magazines, reports and public publications with website publishing control.</p></article><article class="neb-card"><h2>Document Search & Retrieval</h2><p>Search by file number, customer, department, subject, date, category and confidentiality permission.</p></article></div>`;
};
NEBREG.newRecord=()=>NEBUI.modal({title:'Register Official Document',fields:[{name:'owner',label:'Document owner/source',type:'select',options:['Office','Customer','External']},{name:'type',label:'Document type',type:'select',options:['Incoming Letter','Outgoing Letter','Internal Memo','Contract','Customer Document','Legal Document','Report','Publication','Other']},{name:'classification',label:'Confidentiality',type:'select',options:['Internal','Confidential','Highly Confidential','Restricted','Executive Only']},{name:'subject',label:'Subject / title',required:true,full:true},{name:'physical',label:'Physical archive location',placeholder:'Room / Cabinet / Shelf / Box'},{name:'retention',label:'Retention review date',type:'date'},{name:'notes',label:'Registry notes',type:'textarea',full:true}],submitText:'Register & Generate File No.',onSubmit:async v=>{const {data,error}=await supabaseClient.rpc('registry_create_record_pro',{p_owner_type:v.owner,p_record_type:v.type,p_classification:v.classification,p_subject:v.subject,p_physical_location:v.physical,p_retention_until:v.retention||null,p_notes:v.notes});if(error)throw error;NEBUI.toast(`Registered ${data}`,'success');setTimeout(NEBREG.load,100);return true}});
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(document.body.dataset.module==='registry')NEBREG.load()},420));
