const access=document.getElementById('v26Access'),workspace=document.getElementById('v26Workspace');let profile=null;
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function authorize(roles,page){const {data:{user}}=await supabaseClient.auth.getUser();if(!user){access.innerHTML='Please <a href="admin.html">sign in</a> first.';return false;}const {data:p,error}=await supabaseClient.from('admin_users').select('*').eq('user_id',user.id).single();if(error||!p||p.approval_status!=='Approved'||!p.is_active||(roles.length&&!roles.includes(p.role)&&!['CEO','Super Admin','Manager'].includes(p.role))){access.textContent='Approved access is required.';return false;}profile=p;access.classList.add('hidden');workspace.classList.remove('hidden');try{await supabaseClient.rpc('record_staff_login',{p_page:page});}catch{}return true;}
function card(title,body,actions=''){return `<div class="reference-result-card"><strong>${esc(title)}</strong><p>${esc(body||'')}</p><div class="reference-result-actions">${actions}</div></div>`;}
async function init(){if(!await authorize(['Secretary','Customer Care'],'secretary'))return;await Promise.all([visitors(),attendance(),cc(),corr()])}
async function visitors(){const {data,error}=await supabaseClient.from('digital_visits').select('*').in('status',['Waiting at Reception','In Service','Sent to Department']).order('created_at');const r=data||[];secWaiting.textContent=r.filter(x=>x.status==='Waiting at Reception').length;secServing.textContent=r.filter(x=>x.status==='In Service').length;secVisitors.innerHTML=error?esc(error.message):r.map(x=>card(x.visitor_number,x.full_name+' · '+x.purpose+' · '+x.recommended_department,`<button onclick="route('${x.id}')">Route</button><button onclick="serve('${x.id}')">Start Service</button>`)).join('')||'<p>No visitors waiting.</p>'}
window.route=async id=>{const {error}=await supabaseClient.rpc('secretary_route_visit',{p_visit_id:id});if(error)alert(error.message);else visitors()};window.serve=async id=>{await supabaseClient.from('digital_visits').update({status:'In Service',service_started_at:new Date().toISOString()}).eq('id',id);visitors()}
async function attendance(){const {data}=await supabaseClient.rpc('ceo_attendance_today');const r=data||[];secStaffIn.textContent=r.filter(x=>['On Time','Late'].includes(x.status)).length;secAttendance.innerHTML=r.map(x=>card(x.full_name,x.role+' · '+x.status+' · '+(x.check_in_at?new Date(x.check_in_at).toLocaleTimeString():'Not arrived'))).join('')||'<p>No staff records.</p>'}
async function cc(){const {data}=await supabaseClient.from('customer_interactions').select('*').eq('routing_status','Secretary Review').order('created_at',{ascending:false});secCustomerCare.innerHTML=(data||[]).map(x=>card(x.reference,x.full_name+' · '+x.subject+' · '+x.priority,`<button onclick="routeCC('${x.id}')">Route to Department</button>`)).join('')||'<p>No Customer Care records waiting.</p>'}
window.routeCC=async id=>{const {error}=await supabaseClient.rpc('route_customer_interaction',{p_interaction_id:id});if(error)alert(error.message);else cc()}
async function corr(){const {data,error}=await supabaseClient.rpc('staff_correspondence_trays');const r=(data||[]).filter(x=>x.direction==='Incoming');secIncoming.textContent=r.length;secCorrespondence.innerHTML=error?esc(error.message):r.map(x=>card(x.file_number,x.subject+' · '+x.priority+' · '+x.status)).join('')||'<p>No incoming files.</p>'};init();