const access=document.getElementById('v26Access'),workspace=document.getElementById('v26Workspace');let profile=null;
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function authorize(roles,page){const {data:{user}}=await supabaseClient.auth.getUser();if(!user){access.innerHTML='Please <a href="admin.html">sign in</a> first.';return false;}const {data:p,error}=await supabaseClient.from('admin_users').select('*').eq('user_id',user.id).single();if(error||!p||p.approval_status!=='Approved'||!p.is_active||(roles.length&&!roles.includes(p.role)&&!['CEO','Super Admin','Manager'].includes(p.role))){access.textContent='Approved access is required.';return false;}profile=p;access.classList.add('hidden');workspace.classList.remove('hidden');try{await supabaseClient.rpc('record_staff_login',{p_page:page});}catch{}return true;}
function card(title,body,actions=''){return `<div class="reference-result-card"><strong>${esc(title)}</strong><p>${esc(body||'')}</p><div class="reference-result-actions">${actions}</div></div>`;}
async function init(){if(!await authorize([],'staff-room'))return;await Promise.all([posts(),meetings(),leaves(),suggestions()]);}
async function posts(){const {data}=await supabaseClient.from('staff_room_posts').select('*').order('created_at',{ascending:false}).limit(30);staffPosts.innerHTML=(data||[]).map(x=>card(x.title,x.body)).join('')||'<p>No announcements.</p>'}
async function meetings(){const {data}=await supabaseClient.from('staff_meetings').select('*').gte('meeting_at',new Date().toISOString()).order('meeting_at');document.getElementById('meetings').innerHTML=(data||[]).map(x=>card(x.title,new Date(x.meeting_at).toLocaleString()+' · '+(x.agenda||''))).join('')||'<p>No upcoming meetings.</p>'}
async function leaves(){const {data}=await supabaseClient.from('leave_requests').select('*').eq('user_id',profile.user_id).order('created_at',{ascending:false});leaveRequests.innerHTML=(data||[]).map(x=>card(x.request_type,x.status+' · '+x.start_at+' → '+x.end_at)).join('')||'<p>No requests.</p>'}
async function suggestions(){const {data}=await supabaseClient.from('staff_suggestions').select('*').eq('user_id',profile.user_id).order('created_at',{ascending:false});document.getElementById('suggestions').innerHTML=(data||[]).map(x=>card(x.category,x.status+' · '+x.message)).join('')||'<p>No submissions.</p>'}
newStaffPost.onclick=async()=>{const title=prompt('Title:'),body=prompt('Announcement:');if(title&&body){await supabaseClient.from('staff_room_posts').insert({title,body,created_by:profile.user_id});posts()}}
newMeeting.onclick=async()=>{const title=prompt('Meeting title:'),at=prompt('Date & time, e.g. 2026-08-10 10:00:'),agenda=prompt('Agenda:')||'';if(title&&at){await supabaseClient.from('staff_meetings').insert({title,meeting_at:at,agenda,created_by:profile.user_id});meetings()}}
newLeave.onclick=async()=>{const type=prompt('Permission / Leave / Early Departure:','Permission'),start=prompt('Start date/time:'),end=prompt('End date/time:'),reason=prompt('Reason:')||'';if(type&&start&&end){await supabaseClient.from('leave_requests').insert({user_id:profile.user_id,request_type:type,start_at:start,end_at:end,reason,status:'Pending'});leaves()}}
newSuggestion.onclick=async()=>{const category=prompt('Suggestion or Concern:','Suggestion'),message=prompt('Message:');if(message){await supabaseClient.from('staff_suggestions').insert({user_id:profile.user_id,category,message,is_confidential:confirm('Confidential to HR/Management?'),status:'Submitted'});suggestions()}};init();