-- NEBRIN V21 STAFF INVITATION & REFERENCE RECOVERY UPDATE
begin;
alter table public.admin_users add column if not exists email text, add column if not exists phone text, add column if not exists approval_status text not null default 'Approved' check (approval_status in ('Pending','Approved','Rejected')), add column if not exists approved_by uuid references auth.users(id) on delete set null, add column if not exists approved_at timestamptz, add column if not exists created_at timestamptz not null default now();
create table if not exists public.staff_invites(id uuid primary key default gen_random_uuid(),token_hash text unique not null,email text not null,role text not null,department text not null,expires_at timestamptz not null,created_by uuid not null references auth.users(id) on delete cascade,used_by uuid references auth.users(id) on delete set null,used_at timestamptz,created_at timestamptz not null default now());
alter table public.staff_invites enable row level security;
drop policy if exists "management reads staff invites" on public.staff_invites;
create policy "management reads staff invites" on public.staff_invites for select to authenticated using (exists(select 1 from public.admin_users au where au.user_id=auth.uid() and au.role in ('CEO','Super Admin','Manager') and au.approval_status='Approved'));
create or replace function public.create_staff_invite(p_email text,p_role text,p_department text,p_expiry_hours integer default 48) returns text language plpgsql security definer set search_path=public as $$declare plain_token text;begin if not exists(select 1 from public.admin_users where user_id=auth.uid() and role in ('CEO','Super Admin','Manager') and approval_status='Approved' and is_active=true) then raise exception 'Only approved management staff can create invitations.';end if;plain_token:=encode(gen_random_bytes(32),'hex');insert into public.staff_invites(token_hash,email,role,department,expires_at,created_by) values(encode(digest(plain_token,'sha256'),'hex'),lower(trim(p_email)),trim(p_role),trim(p_department),now()+make_interval(hours=>greatest(1,least(p_expiry_hours,168))),auth.uid());return plain_token;end;$$;
revoke all on function public.create_staff_invite(text,text,text,integer) from public;grant execute on function public.create_staff_invite(text,text,text,integer) to authenticated;
create or replace function public.validate_staff_invite(p_token text) returns table(email text,role text,department text) language sql security definer set search_path=public as $$select i.email,i.role,i.department from public.staff_invites i where i.token_hash=encode(digest(trim(p_token),'sha256'),'hex') and i.used_at is null and i.expires_at>now() limit 1;$$;revoke all on function public.validate_staff_invite(text) from public;grant execute on function public.validate_staff_invite(text) to anon,authenticated;
create or replace function public.claim_staff_invite(p_token text,p_user_id uuid,p_full_name text,p_phone text,p_email text) returns boolean language plpgsql security definer set search_path=public as $$declare invite_row public.staff_invites%rowtype;begin if auth.uid() is distinct from p_user_id then raise exception 'Authenticated user mismatch.';end if;select * into invite_row from public.staff_invites where token_hash=encode(digest(trim(p_token),'sha256'),'hex') and used_at is null and expires_at>now() for update;if invite_row.id is null then raise exception 'Invitation is invalid, expired or already used.';end if;if lower(trim(p_email))<>lower(invite_row.email) then raise exception 'Use the same email address that received the invitation.';end if;insert into public.admin_users(user_id,full_name,role,department,email,phone,is_active,approval_status) values(p_user_id,trim(p_full_name),invite_row.role,invite_row.department,lower(trim(p_email)),trim(p_phone),false,'Pending') on conflict(user_id) do update set full_name=excluded.full_name,role=excluded.role,department=excluded.department,email=excluded.email,phone=excluded.phone,is_active=false,approval_status='Pending';update public.staff_invites set used_by=p_user_id,used_at=now() where id=invite_row.id;return true;end;$$;revoke all on function public.claim_staff_invite(text,uuid,text,text,text) from public;grant execute on function public.claim_staff_invite(text,uuid,text,text,text) to authenticated;
create or replace function public.current_staff_is_approved() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.admin_users where user_id=auth.uid() and approval_status='Approved' and is_active=true);$$;revoke all on function public.current_staff_is_approved() from public;grant execute on function public.current_staff_is_approved() to authenticated;
create or replace function public.admin_find_customer_references(p_query text) returns table(record_type text,reference text,full_name text,phone text,email text,service_or_office text,status text,created_at timestamptz) language plpgsql security definer set search_path=public as $$begin if not public.current_staff_is_approved() then raise exception 'Approved staff access is required.';end if;return query select 'Service Application'::text,a.reference,a.full_name,a.phone,coalesce(a.email,''),a.service,a.status,a.created_at from public.applications a where a.deleted_at is null and (lower(a.full_name) like '%'||lower(trim(p_query))||'%' or lower(coalesce(a.email,'')) like '%'||lower(trim(p_query))||'%' or regexp_replace(a.phone,'[^0-9]','','g') like '%'||regexp_replace(trim(p_query),'[^0-9]','','g')||'%') union all select 'Appointment Booking'::text,ap.reference,ap.full_name,ap.phone,coalesce(ap.email,''),ap.office,ap.status,ap.created_at from public.appointments ap where lower(ap.full_name) like '%'||lower(trim(p_query))||'%' or lower(coalesce(ap.email,'')) like '%'||lower(trim(p_query))||'%' or regexp_replace(ap.phone,'[^0-9]','','g') like '%'||regexp_replace(trim(p_query),'[^0-9]','','g')||'%' order by created_at desc limit 25;end;$$;revoke all on function public.admin_find_customer_references(text) from public;grant execute on function public.admin_find_customer_references(text) to authenticated;
commit;
