-- NEBRIN WEBSITE V7 MIGRATION
-- Ensures every standard Admin service also exists in public.services.
-- The customer form already reads all active services directly from this table.

insert into public.services
(name, category, description, price, processing_time, required_documents, is_active)
values
('TIN Registration','Tax Services','Support for individual and business TIN registration.',null,'Processing time depends on TRA.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":false,"note":""}]'::jsonb,true),
('NIDA Application','Government Services','Support for new NIDA applications and document preparation.',null,'Processing time depends on NIDA.','[{"name":"Birth Certificate","required":true,"note":""},{"name":"Local Government Introduction Letter","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""}]'::jsonb,true),
('Birth Certificate Support','Government Services','Application guidance for birth certificate services.',null,'Processing time depends on RITA.','[{"name":"Parent or Guardian NIDA Copy","required":true,"note":""},{"name":"Birth Notification or Supporting Letter","required":false,"note":""}]'::jsonb,true),
('Death Certificate Support','Government Services','Application support for death certificate services.',null,'Processing time depends on RITA.','[{"name":"Applicant NIDA Copy","required":true,"note":""},{"name":"Death Notification or Supporting Letter","required":true,"note":""}]'::jsonb,true),
('Marriage Certificate Support','Government Services','Application support for marriage certificate services.',null,'Processing time depends on RITA.','[{"name":"Spouse NIDA Copies","required":true,"note":""},{"name":"Marriage Supporting Documents","required":true,"note":""}]'::jsonb,true),
('Passport Application','Immigration Services','Support for passport application preparation.',null,'Processing time depends on Immigration.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Birth Certificate","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""}]'::jsonb,true),
('Visa Application','Immigration Services','Support for visa application document preparation.',null,'Processing time depends on the destination authority.','[{"name":"Passport Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Invitation Letter","required":false,"note":""}]'::jsonb,true),
('Driving Licence Services','Government Services','Support for driving licence application or renewal.',null,'Processing time depends on the responsible authority.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Old Driving Licence","required":false,"note":"For renewal where applicable."}]'::jsonb,true),
('Police Clearance Certificate','Government Services','Support for police clearance certificate applications.',null,'Processing time depends on Police services.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""}]'::jsonb,true),
('Company Registration','Business Services','End-to-end assistance with company registration.',null,'Processing time depends on BRELA.','[{"name":"Director NIDA Copies","required":true,"note":""},{"name":"Proposed Company Names","required":true,"note":"Provide at least three options."},{"name":"Director Contact Details","required":true,"note":""}]'::jsonb,true),
('Business Name Registration','Business Services','Registration support for business names.',null,'Processing time depends on BRELA.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Proposed Business Names","required":true,"note":"Provide at least three options."}]'::jsonb,true),
('Business License Processing','Business Services','Guidance and document support for business licensing.',null,'Processing time depends on the local authority.','[{"name":"TIN Certificate","required":true,"note":""},{"name":"Business Registration Certificate","required":true,"note":""},{"name":"Premises Information","required":true,"note":""}]'::jsonb,true),
('Tax Clearance Certificate','Tax Services','Support for tax clearance certificate requirements.',null,'Processing time depends on TRA.','[{"name":"TIN Certificate","required":true,"note":""},{"name":"Tax Supporting Documents","required":true,"note":""}]'::jsonb,true),
('TIN Amendment','Tax Services','Support for amendment of TIN information.',null,'Processing time depends on TRA.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Existing TIN Certificate","required":true,"note":""},{"name":"Supporting Change Document","required":true,"note":""}]'::jsonb,true),
('TRA Services','Tax Services','General support for selected TRA services.',null,'Processing time depends on TRA.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"TIN Certificate","required":false,"note":""}]'::jsonb,true),
('BRELA Services','Business Services','General support for selected BRELA services.',null,'Processing time depends on BRELA.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Business Supporting Documents","required":false,"note":""}]'::jsonb,true),
('RITA Services','Government Services','General support for selected RITA services.',null,'Processing time depends on RITA.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Supporting Civil Document","required":true,"note":""}]'::jsonb,true),
('NSSF Services','Government Services','Support for selected NSSF registration and related services.',null,'Processing time depends on NSSF.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Employment or Business Supporting Document","required":false,"note":""}]'::jsonb,true),
('OSHA Services','Business Services','Support for selected OSHA business compliance services.',null,'Processing time depends on OSHA.','[{"name":"Business Registration Certificate","required":true,"note":""},{"name":"TIN Certificate","required":true,"note":""}]'::jsonb,true),
('HESLB Services','Education Services','Support for selected HESLB application services.',null,'Processing time depends on HESLB.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Academic Supporting Documents","required":true,"note":""}]'::jsonb,true),
('M-Pesa Registration','Mobile Financial Services','Support for M-Pesa registration requirements.',null,'1–3 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Business License","required":false,"note":""}]'::jsonb,true),
('Lipa Number Registration','Mobile Financial Services','Support for business payment and Lipa Number registration.',null,'1–5 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Business License","required":true,"note":""},{"name":"TIN Certificate","required":true,"note":""},{"name":"Passport Photo","required":false,"note":""}]'::jsonb,true),
('Airtel Money Registration','Mobile Financial Services','Support for Airtel Money registration requirements.',null,'1–3 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Business License","required":false,"note":""}]'::jsonb,true),
('Mixx by Yas Registration','Mobile Financial Services','Support for Mixx by Yas registration requirements.',null,'1–3 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Business License","required":false,"note":""}]'::jsonb,true),
('HaloPesa Registration','Mobile Financial Services','Support for HaloPesa registration requirements.',null,'1–3 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Business License","required":false,"note":""}]'::jsonb,true),
('CRDB Account Opening','Banking Services','Support for preparing CRDB account opening requirements.',null,'1–3 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Proof of Address","required":false,"note":""},{"name":"TIN Certificate","required":false,"note":""}]'::jsonb,true),
('NMB Account Opening','Banking Services','Support for preparing NMB account opening requirements.',null,'1–3 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Proof of Address","required":false,"note":""}]'::jsonb,true),
('NBC Account Opening','Banking Services','Support for preparing NBC account opening requirements.',null,'1–3 working days.','[{"name":"NIDA Copy","required":true,"note":""},{"name":"Passport Photo","required":true,"note":""},{"name":"Proof of Address","required":false,"note":""}]'::jsonb,true),
('Website Development','Digital Services','Responsive website design and development.',null,'Agreed after project assessment.','[{"name":"Company Profile or Business Information","required":true,"note":""},{"name":"Logo","required":false,"note":""},{"name":"Sample Content or References","required":false,"note":""}]'::jsonb,true),
('Mobile App Development','Digital Services','Modern mobile application design and development.',null,'Agreed after project assessment.','[{"name":"Project Requirements","required":true,"note":""},{"name":"Logo","required":false,"note":""},{"name":"Reference Screens or Examples","required":false,"note":""}]'::jsonb,true),
('E-commerce Solutions','Digital Services','Online selling platforms and e-commerce setup.',null,'Agreed after project assessment.','[{"name":"Business Information","required":true,"note":""},{"name":"Product or Service List","required":true,"note":""},{"name":"Logo","required":false,"note":""}]'::jsonb,true),
('Logo & Graphic Design','Creative Services','Professional logo, poster, flyer and branding design.',null,'1–7 working days.','[{"name":"Design Brief","required":true,"note":""},{"name":"Reference Images","required":false,"note":""}]'::jsonb,true),
('Digital Marketing','Digital Services','Social media branding, campaigns and content support.',null,'Agreed after project assessment.','[{"name":"Business Information","required":true,"note":""},{"name":"Logo","required":false,"note":""},{"name":"Campaign Goals","required":true,"note":""}]'::jsonb,true),
('CV Writing & Job Application','Employment Services','Professional CV preparation and job application support.',null,'1–3 working days.','[{"name":"Personal Information","required":true,"note":""},{"name":"Academic Certificates","required":false,"note":""},{"name":"Work Experience Details","required":false,"note":""}]'::jsonb,true),
('Entrepreneurship Training','Training Services','Practical entrepreneurship training.',null,'According to the training schedule.','[]'::jsonb,true),
('Business Development Training','Training Services','Training in planning, sales, customer service and operations.',null,'According to the training schedule.','[]'::jsonb,true),
('Youth Recruitment','Employment Services','Youth recruitment, placement and capacity development.',null,'Depends on available opportunities.','[{"name":"CV","required":true,"note":""},{"name":"Academic Certificates","required":false,"note":""},{"name":"NIDA Copy","required":true,"note":""}]'::jsonb,true)
on conflict (name) do update
set
  category = excluded.category,
  description = case when public.services.description = '' then excluded.description else public.services.description end,
  processing_time = case when public.services.processing_time = '' then excluded.processing_time else public.services.processing_time end,
  required_documents = case
    when public.services.required_documents = '[]'::jsonb then excluded.required_documents
    else public.services.required_documents
  end,
  is_active = true;
