export type BookSchema={purpose:string;columns:string[];autoPost:string[];aiExamples:string[]};

const DEFAULT:BookSchema={
 purpose:'Accounting workbook linked to the NEBRIN double-entry engine.',
 columns:['Date','Reference','Particulars','Account Code','Counterparty','Debit','Credit','Balance','Status'],
 autoPost:['General Ledger','Trial Balance','Relevant financial statements'],
 aiExamples:['Prepare the correct accounting entry','Explain the debit and credit treatment','Check this record for accounting errors']
};

export const BOOK_SCHEMAS:Record<string,BookSchema>={
 cash_book:{purpose:'Record all cash and bank receipts/payments and maintain running balances.',columns:['Date','Particulars','Voucher/Ref','Cash Receipts','Bank Receipts','Cash Payments','Bank Payments','Discount','Balance'],autoPost:['General Journal','Cash Ledger','Bank Ledger','Revenue/Expense Ledgers','Trial Balance','Cash Flow'],aiExamples:['Prepare a cash book entry','Classify this receipt or payment','Check the cash balance']},
 petty_cash:{purpose:'Imprest and petty expense control.',columns:['Date','Voucher No.','Particulars','Received','Total Paid','Transport','Stationery','Communication','Refreshment','Other','Balance'],autoPost:['Petty Cash Ledger','Expense Ledgers','General Ledger','Trial Balance'],aiExamples:['Classify these petty cash expenses','Prepare petty cash analysis','Check imprest replenishment']},
 receipts:{purpose:'Register official receipts issued for money received.',columns:['Date','Receipt No.','Payer','Description','Payment Method','Reference','Amount','Account','Status'],autoPost:['Cash/Bank Book','Revenue or Receivable Ledger','General Ledger'],aiExamples:['Prepare receipt accounting','Identify the correct revenue account','Match receipts to invoices']},
 receipt_vouchers:{purpose:'Control and document receipt vouchers.',columns:['Date','Voucher No.','Received From','Purpose','Account','Payment Method','Reference','Amount','Approved By'],autoPost:['Receipts Register','Cash/Bank Book','General Ledger'],aiExamples:['Prepare receipt voucher','Check supporting information','Suggest account classification']},
 payment_vouchers:{purpose:'Authorize and document payments.',columns:['Date','Voucher No.','Payee','Purpose','Expense/Asset Account','Payment Method','Reference','Amount','Approval Status'],autoPost:['Cash/Bank Book','Expense/Asset Ledger','General Ledger','Payables'],aiExamples:['Prepare payment voucher','Classify this payment','Check voucher completeness']},
 expenses:{purpose:'Detailed expense register by category, department and payee.',columns:['Date','Expense Category','Payee','Voucher No.','Department','Payment Method','Tax','Amount','Status'],autoPost:['Expense Ledger','Cash/Bank Book or Payables','General Ledger','Profit & Loss'],aiExamples:['Classify this expense','Prepare expense entry','Check tax treatment']},
 invoices:{purpose:'Customer invoice and billing register.',columns:['Date','Invoice No.','Customer','Service/Product','Taxable Amount','Tax','Total','Paid','Balance','Status'],autoPost:['Sales/Revenue Book','Accounts Receivable','General Ledger','Tax Register'],aiExamples:['Prepare invoice accounting','Calculate invoice balance','Match payment to invoice']},
 revenue:{purpose:'Record earned income by service/revenue category.',columns:['Date','Reference','Customer','Revenue Category','Description','Gross Amount','Tax','Net Revenue','Status'],autoPost:['Revenue Ledger','Receivables/Cash','General Ledger','Profit & Loss'],aiExamples:['Classify revenue','Prepare revenue journal','Check recognition treatment']},
 journal:{purpose:'Journal proper for adjustments, corrections, accruals and transactions not captured in a subsidiary book.',columns:['Date','Particulars','L.F.','Debit Account','Credit Account','Debit Amount','Credit Amount','Narration','Status'],autoPost:['General Ledger','Relevant Subsidiary Ledgers','Trial Balance','Financial Statements'],aiExamples:['Prepare a journal entry','Correct this accounting error','Create an adjusting entry']},
 ledger:{purpose:'Account-by-account record of all postings with running balances.',columns:['Date','Particulars','J.F.','Debit','Credit','Running Balance','Source Book','Source Reference'],autoPost:['Trial Balance','Profit & Loss','Statement of Financial Position'],aiExamples:['Post this journal to ledger','Explain this ledger balance','Find unusual ledger movements']},
 subsidiary_ledgers:{purpose:'Detailed customer, supplier, revenue, expense and other supporting ledgers.',columns:['Date','Account/Party','Reference','Particulars','Debit','Credit','Balance','Source'],autoPost:['General Ledger Control Accounts','Trial Balance'],aiExamples:['Prepare subsidiary posting','Reconcile control account','Explain outstanding balance']},
 receivables:{purpose:'Customer/debtor balances and collections.',columns:['Date','Customer','Invoice/Ref','Description','Debit/Invoiced','Credit/Paid','Balance','Due Date','Status'],autoPost:['Accounts Receivable Control','General Ledger','Aged Receivables','Cash/Bank when paid'],aiExamples:['Prepare debtor statement','Age receivables','Match customer payment']},
 payables:{purpose:'Supplier/creditor balances and payments.',columns:['Date','Supplier','Invoice/Ref','Description','Credit/Purchase','Debit/Paid','Balance','Due Date','Status'],autoPost:['Accounts Payable Control','General Ledger','Aged Payables','Cash/Bank when paid'],aiExamples:['Prepare supplier statement','Age payables','Match supplier payment']},
 chart_accounts:{purpose:'Master list of approved account codes and classifications.',columns:['Account Code','Account Name','Type','Class','Normal Balance','Parent Account','Active'],autoPost:['Journal Validation','Ledger Structure','Reporting Mapping'],aiExamples:['Suggest account code','Classify a new account','Check duplicate accounts']},
 trial_balance:{purpose:'List all ledger balances to confirm total debits equal total credits.',columns:['Account Code','Account Name','L.F.','Debit Balance','Credit Balance','Difference/Flag'],autoPost:['Profit & Loss','Statement of Financial Position','Period-End Review'],aiExamples:['Check trial balance','Find possible imbalance','Explain debit/credit balances']},
 bank_book:{purpose:'Dedicated bank account transaction book.',columns:['Date','Particulars','Cheque/Ref','Deposits','Withdrawals','Bank Charges','Interest','Balance'],autoPost:['Bank Ledger','General Ledger','Bank Reconciliation','Cash Flow'],aiExamples:['Prepare bank book entry','Classify bank charge or interest','Check bank running balance']},
 bank_reconciliation:{purpose:'Reconcile Bank Book/Cash Book balance with bank statement balance.',columns:['Date','Particulars','Book Amount','Statement Amount','Add','Less','Adjusted Book Balance','Reconciled Bank Balance','Status'],autoPost:['Bank Book adjustments','General Ledger for bank-only items','Reconciliation Audit Trail'],aiExamples:['Prepare bank reconciliation','Identify outstanding cheques','Identify deposits not yet credited','Prepare amended cash/bank book']},
 cheques:{purpose:'Cheque issue, receipt and clearance tracking.',columns:['Date','Cheque No.','Payee/Payer','Bank','Purpose','Amount','Issued/Received','Cleared Date','Status'],autoPost:['Bank Book','Payables/Receivables','General Ledger'],aiExamples:['Check uncleared cheques','Prepare cheque register entry','Explain stale/outstanding cheque']},
 budgets:{purpose:'Approved budgets and actual performance monitoring.',columns:['Period','Department','Budget Line','Approved Budget','Actual','Committed','Variance','Variance %','Status'],autoPost:['Management Reports','Budget vs Actual','Cashflow Planning'],aiExamples:['Analyse budget variance','Prepare budget forecast','Flag overspending']},
 fixed_assets:{purpose:'Complete fixed asset register.',columns:['Asset ID','Description','Category','Purchase Date','Cost','Location','Custodian','Useful Life','Depreciation Method','Accumulated Depreciation','NBV','Status'],autoPost:['Fixed Asset Ledger','Depreciation Schedule','General Ledger','Statement of Financial Position'],aiExamples:['Classify fixed asset','Calculate depreciation','Prepare disposal entry']},
 depreciation:{purpose:'Periodic depreciation calculation and posting.',columns:['Asset ID','Asset','Cost','Method','Rate/Life','Opening Accumulated Depreciation','Period Depreciation','Closing Accumulated Depreciation','NBV'],autoPost:['Depreciation Expense','Accumulated Depreciation','General Ledger','Financial Statements'],aiExamples:['Calculate depreciation','Check useful life','Prepare depreciation journal']},
 payroll:{purpose:'Payroll accounting register and salary liabilities.',columns:['Period','Employee','Gross Pay','Allowances','Tax','Pension/Statutory','Other Deductions','Net Pay','Payment Status'],autoPost:['Payroll Expense Ledger','Salary Payable','Tax/Statutory Payables','Cash/Bank'],aiExamples:['Prepare payroll accounting','Check payroll deductions','Prepare payroll journal']},
 tax:{purpose:'Tax/VAT computation, liability and payment tracking.',columns:['Tax Type','Period','Reference','Taxable Amount','Output Tax','Input Tax','Tax Liability','Paid','Balance','Due Date','Status'],autoPost:['Tax Ledgers','General Ledger','Payables/Cash'],aiExamples:['Prepare VAT summary','Check tax liability','Explain tax posting']},
 withholding_tax:{purpose:'Withholding tax deductions and remittance control.',columns:['Date','Supplier/Payee','Invoice/Ref','Gross Amount','WHT Rate','WHT Amount','Net Paid','Remittance Ref','Status'],autoPost:['Withholding Tax Payable','Expense/Asset Ledger','Cash/Bank','General Ledger'],aiExamples:['Calculate withholding tax','Prepare WHT entry','Check remittance balance']},
 adjustments:{purpose:'Formal register of approved adjusting and correcting journal entries.',columns:['Date','Adjustment Ref','Reason','Debit Account','Credit Account','Debit','Credit','Prepared By','Approved By','Status'],autoPost:['General Journal','General Ledger','Trial Balance'],aiExamples:['Prepare correction entry','Prepare year-end adjustment','Explain impact on accounts']},
 accruals:{purpose:'Track accrued expenses/income and prepayments with reversals.',columns:['Date','Type','Description','Account','Counter Account','Amount','Start Period','End Period','Reversal Date','Status'],autoPost:['General Journal','Expense/Income Ledger','Asset/Liability Ledger','Financial Statements'],aiExamples:['Prepare accrual entry','Prepare prepayment schedule','Prepare reversal']},
 closing:{purpose:'Period-end closing and opening balance control.',columns:['Period','Closing Entry Ref','Account','Debit','Credit','Closing Balance','Carry Forward','Status'],autoPost:['Retained Earnings/Capital','Opening Balances','Financial Statements Archive'],aiExamples:['Prepare closing entries','Check accounts to close','Explain carry-forward balances']},
 profit_loss:{purpose:'Generated income statement from posted revenue and expense ledgers.',columns:['Section','Account','Current Period','Prior Period','Variance','Notes'],autoPost:['Management Reporting','Equity/Retained Earnings'],aiExamples:['Explain profit or loss','Analyse expense trends','Prepare management commentary']},
 balance_sheet:{purpose:'Generated statement of assets, liabilities and equity.',columns:['Section','Account','Current Balance','Prior Balance','Variance','Notes'],autoPost:['Management Reporting','Audit Financial Statements'],aiExamples:['Explain financial position','Analyse working capital','Check balance sheet classification']},
 cash_flow:{purpose:'Generated cash flow statement by operating, investing and financing activities.',columns:['Activity','Description','Cash Inflow','Cash Outflow','Net Cash Flow','Period'],autoPost:['Management Reporting','Financial Statements Archive'],aiExamples:['Classify cash flow','Explain operating cash flow','Prepare cash flow analysis']},
 equity:{purpose:'Movement in capital, reserves and retained earnings.',columns:['Equity Component','Opening Balance','Additions','Profit/Loss','Distributions','Transfers','Closing Balance'],autoPost:['Statement of Financial Position','Financial Statements Archive'],aiExamples:['Prepare equity movement','Explain retained earnings','Check owner distributions']},
 spreadsheet:{purpose:'Excel-style accounting workpapers linked to controlled accounting records.',columns:['Row','Column','Formula/Value','Linked Account/Book','Period','Owner','Status'],autoPost:['Supporting Workpapers only; official posting occurs through approved accounting entries'],aiExamples:['Build accounting schedule','Create formula logic','Summarize this workbook']},
 supporting_docs:{purpose:'Index source documents supporting financial records.',columns:['Date','Document Type','Reference','Related Book','Related Entry','Party','File','Verified','Status'],autoPost:['Audit Evidence Index','Accounting Audit Trail'],aiExamples:['Identify missing support','Match document to transaction','Summarize supporting document']},
 audit_trail:{purpose:'Immutable history of accounting actions and postings.',columns:['Timestamp','User','Action','Source Book','Reference','Before','After','Approval','IP/Device'],autoPost:['Internal Audit','Security Monitoring'],aiExamples:['Summarize audit trail','Find unusual changes','Trace this transaction']},
 reports_archive:{purpose:'Controlled archive of finalized financial reports.',columns:['Period','Report Type','Version','Prepared By','Reviewed By','Approved By','Generated At','File/Reference','Status'],autoPost:['Audit File Room','Management Records'],aiExamples:['Compare report versions','Summarize report','Explain period changes']}
};

export function schemaFor(key:string):BookSchema{return BOOK_SCHEMAS[key]||DEFAULT}
