import {useEffect,useState} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import type {FinanceGovernancePayload,FinancePayload} from '../types/app';
import {cancelPayment,decideBankPayment,decideFinanceAuditAccess,decideFinanceSignature,decideFinanceStaffing,getFinanceAuthorizations,getFinanceGovernance,recordPaymentCollection,submitFinanceStaffing,verifyPayment} from '../lib/api';
import {Card} from './Card';
import {InternalAuditWorkspace} from './InternalAuditWorkspace';

const STAFF_COUNTS=[1,2,3,4,5,6,7,8,9,10];
const STAFF_REASONS=['Increased workload / customer demand','New branch, service or work station','Shift coverage / extended service hours','Separation of duties / internal control','Replacement for vacant position','Work backlog / delayed processing','Temporary peak workload','Department expansion'];
const STAFF_SKILLS=['Bookkeeping','Cash handling','Bank & mobile money reconciliation','Accounting software','Excel / spreadsheets','Financial reporting','Budgeting','Tax & statutory compliance','Customer service','Payment processing','Audit & internal controls','Records & document management'];

export function FinanceCentre({payload,onRefresh}:{payload:FinancePayload|null;onRefresh:()=>Promise<void>}){
 const[busy,setBusy]=useState<string|null>(null);const[msg,setMsg]=useState<string|null>(null);const[gov,setGov]=useState<FinanceGovernancePayload['data']|null>(null);const[authz,setAuthz]=useState<any>(null);const[staffReason,setStaffReason]=useState('');const[staffSkills,setStaffSkills]=useState<string[]>([]);const[staffCount,setStaffCount]=useState(1);
 async function refreshGov(){try{const[x,a]=await Promise.all([getFinanceGovernance(),getFinanceAuthorizations()]);setGov(x.data);setAuthz(a.data)}catch(e){setMsg(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{refreshGov()},[]);if(!payload)return null;const q=payload.payment_requests||[];
 async function run(id:string,fn:()=>Promise<any>){try{setBusy(id);setMsg(null);await fn();await Promise.all([onRefresh(),refreshGov()])}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 function toggleSkill(skill:string){setStaffSkills(c=>c.includes(skill)?c.filter(x=>x!==skill):[...c,skill])}
 async function requestStaff(role:'CASHIER'|'ACCOUNTANT'){await submitFinanceStaffing(role,staffReason,staffCount,staffSkills.join(', '));setStaffReason('');setStaffSkills([]);setStaffCount(1)}
 const canSeePayments=!!gov&&(gov.capabilities.cashier||gov.capabilities.accounting||gov.capabilities.treasury||gov.role_code==='CEO'||gov.role_code==='MANAGER');const canCollect=!!gov?.capabilities.cashier;const canVerify=!!gov?.capabilities.accounting&&gov?.role_code==='ACCOUNTANT';const canCancel=!!gov&&(gov.capabilities.treasury||gov.role_code==='CEO'||gov.role_code==='MANAGER');const isTreasurer=gov?.role_code==='TREASURER';const canInternalAudit=!!gov&&['TREASURER','INTERNAL_AUDITOR','MANAGER','CEO','SUPER_ADMIN'].includes(gov.role_code);const staffingReady=!!staffReason&&staffSkills.length>0;
 return <>
 <Card title="Finance Command Centre">{gov?<><Text style={s.role}>{gov.role_code.replaceAll('_',' ')}</Text>{gov.read_only?<Text style={s.readonly}>READ ONLY AUDIT ACCESS</Text>:null}
 {isTreasurer&&gov.capabilities.staffing_request?<View style={s.hodBox}><Text style={s.hodTitle}>Head of Department — Finance Staffing</Text><Text style={s.hodText}>Select the number of employees, the staffing reason and the required skills. Accountant and Cashier remain separate roles with their own duties.</Text><ChoiceSection title="Number required"><View style={s.choiceWrap}>{STAFF_COUNTS.map(n=><Choice key={n} label={String(n)} selected={staffCount===n} onPress={()=>setStaffCount(n)} compact/>)}</View></ChoiceSection><ChoiceSection title="Reason / staffing need"><View style={s.choiceWrap}>{STAFF_REASONS.map(x=><Choice key={x} label={x} selected={staffReason===x} onPress={()=>setStaffReason(x)}/>)}</View></ChoiceSection><ChoiceSection title="Required skills / qualifications"><Text style={s.help}>Choose one or more according to the department need.</Text><View style={s.choiceWrap}>{STAFF_SKILLS.map(x=><Choice key={x} label={x} selected={staffSkills.includes(x)} onPress={()=>toggleSkill(x)}/>)}</View></ChoiceSection><View style={s.selectionSummary}><Text style={s.summaryTitle}>Selected requirement</Text><Text>Employees: {staffCount}</Text><Text>Reason: {staffReason||'Not selected'}</Text><Text>Skills: {staffSkills.length?staffSkills.join(', '):'Not selected'}</Text></View><View style={s.actions}><Pressable disabled={!!busy||!staffingReady} style={[s.ok,(!!busy||!staffingReady)&&s.disabled]} onPress={()=>run('staff-cashier',()=>requestStaff('CASHIER'))}><Text style={s.white}>Request Additional Cashier</Text></Pressable><Pressable disabled={!!busy||!staffingReady} style={[s.ok,(!!busy||!staffingReady)&&s.disabled]} onPress={()=>run('staff-accountant',()=>requestStaff('ACCOUNTANT'))}><Text style={s.white}>Request Additional Accountant</Text></Pressable></View><Text style={s.h}>Recent Staffing Requests</Text>{(gov.staffing_requests||[]).slice(0,10).map(x=><View key={x.id} style={s.row}><Text style={s.title}>{x.request_number} · {x.position_title}</Text><Text>{x.status}{x.current_holder?` · ${x.current_holder}`:''}</Text><Text style={s.meta}>{x.reason}</Text></View>)}{!(gov.staffing_requests||[]).length?<Text>No Finance staffing requests submitted yet.</Text>:null}</View>:null}
 <View style={s.grid}><Metric n={gov.books.invoices} t="Invoices"/><Metric n={gov.books.receipts} t="Receipts"/><Metric n={gov.books.journals} t="Journals"/><Metric n={gov.books.transactions} t="Transactions"/></View>
 {gov.capabilities.cashier?<Section title="Cashier"><Text>Receipts today: {gov.cashier.receipts_today}</Text><Text>Collected today: TZS {Number(gov.cashier.amount_received_today||0).toLocaleString()}</Text><Text>Transactions today: {gov.cashier.transactions_today}</Text></Section>:null}
 {gov.capabilities.accounting?<Section title="Accounts"><Text>Open invoices: {gov.accounting.open_invoices}</Text><Text>Draft journals: {gov.accounting.draft_journals}</Text><Text>Pending expenses: {gov.accounting.pending_expenses}</Text><Text>Trial balance lines: {gov.accounting.trial_balance_lines}</Text></Section>:null}
 {gov.capabilities.treasury?<Section title="Treasury"><Text>Active bank accounts: {gov.treasury.active_bank_accounts}</Text><Text>Approved budgets: {gov.treasury.approved_budgets}</Text><Text>Uncleared cheques: {gov.treasury.uncleared_cheques}</Text></Section>:null}
 {canInternalAudit?<InternalAuditWorkspace onChanged={refreshGov}/>:null}
 {isTreasurer?<><Section title="Financial Signatures"><Text>All financial documents requiring Treasurer signature appear here.</Text>{(authz?.signature_requests||[]).map((x:any)=><View key={x.id} style={s.row}><Text style={s.title}>{x.document_type} · {x.document_reference}</Text><Text>{x.title}</Text><Text style={s.meta}>TZS {Number(x.amount||0).toLocaleString()} · {x.status}</Text>{x.status==='Pending'?<View style={s.actions}><Pressable disabled={!!busy} style={s.ok} onPress={()=>run(x.id,()=>decideFinanceSignature(x.id,'Signed','Signed by Treasurer'))}><Text style={s.white}>Sign</Text></Pressable><Pressable disabled={!!busy} style={s.danger} onPress={()=>run(x.id,()=>decideFinanceSignature(x.id,'Rejected','Rejected by Treasurer'))}><Text style={s.white}>Reject</Text></Pressable></View>:null}</View>)}{!(authz?.signature_requests||[]).length?<Text>No financial documents awaiting signature.</Text>:null}</Section><Section title="Bank Payment Authorization"><Text>Treasurer authorizes bank/payment instructions before release.</Text>{(authz?.bank_payment_approvals||[]).map((x:any)=><View key={x.id} style={s.row}><Text style={s.title}>{x.payment_reference} · TZS {Number(x.amount||0).toLocaleString()}</Text><Text>{x.beneficiary_name}</Text><Text style={s.meta}>{x.bank_name||'Payment account'} · {x.status}</Text>{x.status==='Pending'?<View style={s.actions}><Pressable disabled={!!busy} style={s.ok} onPress={()=>run(x.id,()=>decideBankPayment(x.id,'Approved','Authorized by Treasurer'))}><Text style={s.white}>Authorize Payment</Text></Pressable><Pressable disabled={!!busy} style={s.danger} onPress={()=>run(x.id,()=>decideBankPayment(x.id,'Rejected','Rejected by Treasurer'))}><Text style={s.white}>Reject</Text></Pressable></View>:null}</View>)}{!(authz?.bank_payment_approvals||[]).length?<Text>No bank payments awaiting authorization.</Text>:null}</Section></>:null}
 {gov.capabilities.staffing_decide?<Section title="Finance Staffing Approvals">{(gov.staffing_requests||[]).filter(x=>x.current_holder==='Manager'&&!x.manager_decision).map(x=><View key={x.id} style={s.row}><Text style={s.title}>{x.request_number} · {x.position_title}</Text><Text>{x.reason}</Text><View style={s.actions}><Pressable disabled={!!busy} style={s.ok} onPress={()=>run(x.id,()=>decideFinanceStaffing(x.id,'Approved','Approved for HR recruitment'))}><Text style={s.white}>Approve</Text></Pressable><Pressable disabled={!!busy} style={s.danger} onPress={()=>run(x.id,()=>decideFinanceStaffing(x.id,'Rejected','Not approved'))}><Text style={s.white}>Reject</Text></Pressable></View></View>)}{!(gov.staffing_requests||[]).some(x=>x.current_holder==='Manager'&&!x.manager_decision)?<Text>No Finance staffing requests awaiting decision.</Text>:null}</Section>:null}
 {gov.capabilities.external_audit_read?<Section title="External Audit Room"><Text>Read-only access to accounting books and audit trail.</Text><Text>Audit events visible: {gov.audit_events.length}</Text></Section>:null}
 {gov.capabilities.external_audit_decide?<Section title="External Audit Access Requests">{gov.audit_access.filter(x=>x.status==='Pending').map(x=><View key={x.id} style={s.row}><Text style={s.title}>{x.auditor_name||'External Auditor'}</Text><Text>{x.purpose}</Text><Text style={s.meta}>{x.audit_scope}</Text><View style={s.actions}><Pressable disabled={!!busy} style={s.ok} onPress={()=>run(x.id,()=>decideFinanceAuditAccess(x.id,'Approved'))}><Text style={s.white}>Approve</Text></Pressable><Pressable disabled={!!busy} style={s.danger} onPress={()=>run(x.id,()=>decideFinanceAuditAccess(x.id,'Rejected'))}><Text style={s.white}>Reject</Text></Pressable></View></View>)}{!gov.audit_access.some(x=>x.status==='Pending')?<Text>No pending external audit requests.</Text>:null}</Section>:null}
 </>:<Text>Loading finance governance…</Text>}{msg?<Text style={s.err}>{msg}</Text>:null}</Card>
 {canSeePayments?<Card title="Finance & Customer Payments"><View style={s.stats}><Text>Generated {payload.summary.generated}</Text><Text>Paid {payload.summary.paid}</Text><Text>Cancelled {payload.summary.cancelled}</Text></View><Text style={s.h}>Payment Queue</Text>{q.slice(0,30).map(x=><View key={x.id} style={s.row}><Text style={s.title}>{x.bill_reference} · TZS {Number(x.amount||0).toLocaleString()}</Text><Text>{x.provider} · {x.payment_type}</Text><Text style={s.meta}>{x.application_reference||'Application'} · {x.status}</Text><View style={s.actions}>{x.status==='Generated'&&canCollect?<Pressable disabled={!!busy} style={s.ok} onPress={()=>run(x.id,()=>recordPaymentCollection(x.id))}><Text style={s.white}>{busy===x.id?'Working…':'Record Collected'}</Text></Pressable>:null}{x.status==='Submitted'&&canVerify?<Pressable disabled={!!busy} style={s.ok} onPress={()=>run(x.id,()=>verifyPayment(x.id))}><Text style={s.white}>{busy===x.id?'Working…':'Verify Paid'}</Text></Pressable>:null}{['Generated','Submitted'].includes(x.status)&&canCancel?<Pressable disabled={!!busy} style={s.cancel} onPress={()=>run(x.id,()=>cancelPayment(x.id))}><Text>Cancel Bill</Text></Pressable>:null}</View></View>)}{!q.length?<Text>No payment requests currently waiting.</Text>:null}<Text style={s.h}>Active Payment Methods</Text>{payload.payment_methods.map(x=><View key={x.id} style={s.row}><Text style={s.title}>{x.provider}</Text><Text>{x.payment_type}{x.account_number?` · ${x.account_number}`:''}</Text><Text style={s.meta}>{x.account_name||''}</Text></View>)}</Card>:null}</>;
}
function ChoiceSection({title,children}:{title:string;children:any}){return <View style={s.choiceSection}><Text style={s.choiceTitle}>{title}</Text>{children}</View>}
function Choice({label,selected,onPress,compact=false}:{label:string;selected:boolean;onPress:()=>void;compact?:boolean}){return <Pressable onPress={onPress} style={[s.choice,compact&&s.choiceCompact,selected&&s.choiceSelected]}><Text style={[s.choiceText,selected&&s.choiceTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
function Metric({n,t}:{n:number;t:string}){return <View style={s.metric}><Text style={s.num}>{n}</Text><Text style={s.meta}>{t}</Text></View>}
function Section({title,children}:{title:string;children:any}){return <View style={s.section}><Text style={s.h}>{title}</Text>{children}</View>}
const s=StyleSheet.create({stats:{flexDirection:'row',flexWrap:'wrap',gap:12,marginBottom:10},role:{fontWeight:'900',fontSize:16,color:'#0b5d45'},readonly:{fontWeight:'900',color:'#9b1c1c',marginTop:4},hodBox:{borderWidth:1,borderColor:'#bbd8cf',backgroundColor:'#f2f8f6',borderRadius:14,padding:14,marginTop:14},hodTitle:{fontWeight:'900',fontSize:17,color:'#0b5d45'},hodText:{color:'#334155',marginTop:5,lineHeight:19},choiceSection:{marginTop:14},choiceTitle:{fontWeight:'900',fontSize:14,color:'#14213d',marginBottom:7},help:{fontSize:12,color:'#64748b',marginBottom:7},choiceWrap:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{borderWidth:1,borderColor:'#cbd5e1',backgroundColor:'#fff',borderRadius:10,paddingVertical:9,paddingHorizontal:10},choiceCompact:{minWidth:42,alignItems:'center'},choiceSelected:{borderColor:'#0b5d45',backgroundColor:'#dff1eb'},choiceText:{fontSize:13,color:'#334155'},choiceTextSelected:{fontWeight:'900',color:'#0b5d45'},selectionSummary:{backgroundColor:'#fff',borderRadius:10,padding:10,marginTop:14,gap:3},summaryTitle:{fontWeight:'900',color:'#14213d'},grid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},metric:{width:'47%',backgroundColor:'#eef6f3',padding:12,borderRadius:12},num:{fontWeight:'900',fontSize:25,color:'#08745a'},section:{borderTopWidth:1,borderTopColor:'#e5e7eb',marginTop:14,paddingTop:4,gap:4},h:{fontWeight:'900',fontSize:16,marginTop:12,color:'#14213d'},row:{borderTopWidth:1,borderTopColor:'#e5e7eb',paddingVertical:11,gap:4},title:{fontWeight:'900'},meta:{fontSize:12,color:'#64748b'},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10},ok:{backgroundColor:'#0b5d45',padding:9,borderRadius:9},danger:{backgroundColor:'#9b1c1c',padding:9,borderRadius:9},cancel:{backgroundColor:'#e2e8f0',padding:9,borderRadius:9},disabled:{opacity:.5},white:{color:'#fff',fontWeight:'800'},err:{color:'#9b1c1c',marginVertical:8}});
