import {useEffect,useState} from 'react';
import {Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {attachFinanceAuditSource,createFinanceInternalAudit,createFinanceInternalAuditFinding,getFinanceAuditFileRoom,getFinanceAuditFinancialReport,getFinanceAuditRecordDetail,getFinanceInternalAudit,respondFinanceInternalAuditFinding,verifyFinanceInternalAuditAction} from '../lib/api';
const AUDIT_TYPES=['Risk-Based Review','Compliance Audit','Operational Audit','Financial Audit','Fraud / Investigation','Follow-up Audit'];
const RISK_LEVELS=['Low','Medium','High','Critical'];
const FILE_CATEGORIES=['Invoices','Receipts','Transactions','Expenses','Journals','Trial Balance','Bank Accounts','Budgets','Cheques'];
export function InternalAuditWorkspace({onChanged}:{onChanged?:()=>Promise<void>|void}){
 const[data,setData]=useState<any>(null),[busy,setBusy]=useState<string|null>(null),[msg,setMsg]=useState<string|null>(null),[open,setOpen]=useState<string|null>(null),[fileRoom,setFileRoom]=useState<any>(null),[recordDetail,setRecordDetail]=useState<any>(null),[report,setReport]=useState<any>(null),[fileCategory,setFileCategory]=useState('Invoices'),[selectedAudit,setSelectedAudit]=useState(''),[auditType,setAuditType]=useState('Risk-Based Review'),[auditArea,setAuditArea]=useState(''),[auditRisk,setAuditRisk]=useState('Medium'),[auditTitle,setAuditTitle]=useState(''),[auditObjective,setAuditObjective]=useState(''),[auditScope,setAuditScope]=useState(''),[findingEngagement,setFindingEngagement]=useState(''),[findingCategory,setFindingCategory]=useState('Control Weakness'),[findingRisk,setFindingRisk]=useState('Medium'),[findingTitle,setFindingTitle]=useState(''),[findingCondition,setFindingCondition]=useState(''),[findingCriteria,setFindingCriteria]=useState(''),[findingCause,setFindingCause]=useState(''),[findingEffect,setFindingEffect]=useState(''),[findingRecommendation,setFindingRecommendation]=useState(''),[responseFinding,setResponseFinding]=useState(''),[responseText,setResponseText]=useState(''),[correctiveAction,setCorrectiveAction]=useState(''),[dueDate,setDueDate]=useState('');
 async function refresh(){try{setMsg(null);const r=await getFinanceInternalAudit();const d=r.data||{};setData(d);const es=Array.isArray(d.engagements)?d.engagements:[];if(!selectedAudit&&es.length)setSelectedAudit(es[0].id)}catch(e){setMsg(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{refresh()},[]);
 async function run(id:string,fn:()=>Promise<any>){try{setBusy(id);setMsg(null);await fn();await refresh();if(onChanged)await onChanged()}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 async function loadFiles(cat=fileCategory){try{setBusy('files');setMsg(null);setRecordDetail(null);const r=await getFinanceAuditFileRoom(cat);setFileRoom(r.data||{});setFileCategory(cat)}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 async function openRecord(x:any,i:number){try{setBusy(`read-${i}`);setMsg(null);const r=await getFinanceAuditRecordDetail(fileCategory,String(x.id||x.reference||i));setRecordDetail(r.data||{});setOpen('files')}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 async function loadReport(){try{setBusy('report');setMsg(null);const r=await getFinanceAuditFinancialReport();setReport(r.data||{})}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(null)}}
 if(!data)return <View style={s.box}><Text style={s.h}>Internal Audit</Text><Text>{msg||'Loading…'}</Text></View>;
 const cap=data.capabilities||{},summary=data.summary||{},engagements=Array.isArray(data.engagements)?data.engagements:[],findings=Array.isArray(data.findings)?data.findings:[],actions=Array.isArray(data.actions)?data.actions:[],areas=Array.isArray(data.audit_areas)?data.audit_areas:[];
 const toggle=(k:string)=>setOpen(v=>v===k?null:k);
 async function createAudit(){await createFinanceInternalAudit(auditType,auditTitle.trim()||auditArea||`${auditType} - Finance`,auditObjective.trim()||`Evaluate controls, compliance and risk in ${auditArea||'Finance & Accounts'}.`,auditScope.trim()||auditArea||'Finance & Accounts',auditRisk);setAuditTitle('');setAuditObjective('');setAuditScope('');setOpen('engagements')}
 async function createFinding(){await createFinanceInternalAuditFinding(findingEngagement,findingCategory,findingTitle.trim(),findingCondition.trim(),findingCriteria.trim(),findingCause.trim(),findingEffect.trim(),findingRisk,findingRecommendation.trim());setFindingTitle('');setFindingCondition('');setFindingCriteria('');setFindingCause('');setFindingEffect('');setFindingRecommendation('')}
 async function submitResponse(){await respondFinanceInternalAuditFinding(responseFinding,responseText.trim(),correctiveAction.trim(),dueDate.trim()||undefined);setResponseText('');setCorrectiveAction('');setDueDate('')}
 async function attachRecord(x:any,i:number){if(!selectedAudit)throw new Error('Select an Audit Engagement first.');await attachFinanceAuditSource(selectedAudit,fileCategory,String(x.id||x.reference||i),x.reference||x.title||fileCategory,'Linked from Finance Audit File Room')}
 return <View style={s.box}>
  <Text style={s.h}>Internal Audit & Assurance</Text><Text style={s.note}>Audit workspace connected directly to Finance records, source documents and financial reporting.</Text>
  <View style={s.metrics}><Metric n={summary.active_engagements||0} label="Active audits"/><Metric n={summary.open_findings||0} label="Open findings"/><Metric n={summary.high_critical_findings||0} label="High/Critical"/><Metric n={summary.overdue_actions||0} label="Overdue actions"/></View>
  <Drop title="Finance Audit File Room" open={open==='files'} onPress={()=>{toggle('files');if(open!=='files'&&!fileRoom)loadFiles()}}><Text style={s.note}>Open Finance registers and read the complete accounting record. Auditor access is READ ONLY: no source amount, status, posting, account, receipt, invoice or supporting record can be changed here.</Text>{cap.execute?<><Label text="Attach evidence to Audit Engagement"/>{engagements.length?<View style={s.wrap}>{engagements.map((x:any)=><Choice key={x.id} label={`${x.audit_reference} · ${x.title}`} selected={selectedAudit===x.id} onPress={()=>setSelectedAudit(x.id)}/>)}</View>:<Text style={s.warn}>Create an Audit Engagement first before attaching evidence.</Text>}</>:null}<Label text="Finance register"/><View style={s.wrap}>{FILE_CATEGORIES.map(x=><Choice key={x} label={x} selected={fileCategory===x} onPress={()=>loadFiles(x)}/>)}</View>{busy==='files'?<Text style={s.note}>Loading {fileCategory}…</Text>:null}{recordDetail?<ReadOnlyFile data={recordDetail} onClose={()=>setRecordDetail(null)}/>:null}{fileRoom?<><Text style={s.count}>Records: {fileRoom.count||0}</Text>{(fileRoom.records||[]).map((x:any,i:number)=><View key={`${x.id||i}`} style={s.row}><Text style={s.rowTitle}>{x.reference||x.title||fileCategory}</Text><Text>{x.description||x.status||''}</Text>{x.amount!=null?<Text style={s.meta}>TZS {Number(x.amount).toLocaleString()}</Text>:null}{x.document_path?<Text style={s.good}>Supporting document linked ✓</Text>:null}<View style={s.actions}><Pressable disabled={!!busy} style={[s.read,!!busy&&s.disabled]} onPress={()=>openRecord(x,i)}><Text style={s.white}>{busy===`read-${i}`?'Opening…':'Open & Read File'}</Text></Pressable>{cap.execute?<Pressable disabled={!!busy||!selectedAudit} style={[s.mini,(!!busy||!selectedAudit)&&s.disabled]} onPress={()=>run(`attach-${i}`,()=>attachRecord(x,i))}><Text style={s.white}>{selectedAudit?'Attach as Audit Evidence':'Select Audit First'}</Text></Pressable>:null}</View></View>)}{!(fileRoom.records||[]).length?<Text>No records found in this register.</Text>:null}</>:null}</Drop>
  <Drop title="Financial Statements & Audit Report" open={open==='report'} onPress={()=>{toggle('report');if(open!=='report'&&!report)loadReport()}}><Text style={s.note}>Generated from the same Finance books used by Cashier, Accountant and Treasurer.</Text>{report?<><View style={s.metrics}><Metric n={report.statement_summary?.revenue||report.totals?.invoiced||0} label="Revenue / Invoiced (TZS)"/><Metric n={report.statement_summary?.expenses||report.totals?.expenses||0} label="Expenses (TZS)"/><Metric n={report.statement_summary?.cash_collected||report.totals?.received||0} label="Cash received (TZS)"/><Metric n={report.totals?.outstanding_receivables||0} label="Receivables (TZS)"/></View><Text style={s.subTitle}>Trial Balance</Text>{(report.trial_balance||[]).map((x:any,i:number)=><View key={i} style={s.row}><Text style={s.rowTitle}>{x.account_name}</Text><Text style={s.meta}>Debit {Number(x.total_debit??x.debit??0).toLocaleString()} · Credit {Number(x.total_credit??x.credit??0).toLocaleString()} · Balance {Number(x.balance||0).toLocaleString()}</Text></View>)}{!(report.trial_balance||[]).length?<Text>No trial-balance lines recorded yet.</Text>:null}</>:<Text>{busy==='report'?'Loading financial statements…':'Open to load the current financial statements.'}</Text>}</Drop>
  <Drop title="Audit Coverage" open={open==='coverage'} onPress={()=>toggle('coverage')}><View style={s.wrap}>{areas.map((x:string)=><View key={x} style={s.tag}><Text style={s.tagText}>{x}</Text></View>)}</View></Drop>
  {cap.execute?<Drop title="Start New Internal Audit" open={open==='create'} onPress={()=>toggle('create')}><Label text="Audit type"/><View style={s.wrap}>{AUDIT_TYPES.map(x=><Choice key={x} label={x} selected={auditType===x} onPress={()=>setAuditType(x)}/>)}</View><Label text="Audit area"/><View style={s.wrap}>{areas.map((x:string)=><Choice key={x} label={x} selected={auditArea===x} onPress={()=>setAuditArea(x)}/>)}</View><Label text="Risk rating"/><View style={s.wrap}>{RISK_LEVELS.map(x=><Choice key={x} label={x} selected={auditRisk===x} onPress={()=>setAuditRisk(x)}/>)}</View><TextInput style={s.input} placeholder="Audit title" value={auditTitle} onChangeText={setAuditTitle}/><TextInput style={s.input} placeholder="Objective" value={auditObjective} onChangeText={setAuditObjective} multiline/><TextInput style={s.input} placeholder="Scope" value={auditScope} onChangeText={setAuditScope} multiline/><Pressable disabled={!!busy||!auditArea} style={[s.primary,(!auditArea||!!busy)&&s.disabled]} onPress={()=>run('create',createAudit)}><Text style={s.white}>{busy==='create'?'Creating…':'Create Audit Engagement'}</Text></Pressable></Drop>:null}
  <Drop title={`Audit Engagements (${engagements.length})`} open={open==='engagements'} onPress={()=>toggle('engagements')}>{engagements.map((x:any)=><Pressable key={x.id} style={[s.row,selectedAudit===x.id&&s.selectedRow]} onPress={()=>setSelectedAudit(x.id)}><Text style={s.rowTitle}>{x.audit_reference} · {x.title}</Text><Text>{x.audit_type} · {x.risk_rating} Risk</Text><Text style={s.meta}>{x.status} · {x.scope}</Text>{selectedAudit===x.id?<Text style={s.good}>Current audit file ✓</Text>:null}</Pressable>)}{!engagements.length?<Text>No internal audit engagements yet.</Text>:null}</Drop>
  {cap.execute&&engagements.length?<Drop title="Record Audit Finding" open={open==='finding'} onPress={()=>toggle('finding')}><Label text="Engagement"/><View style={s.wrap}>{engagements.map((x:any)=><Choice key={x.id} label={x.audit_reference} selected={findingEngagement===x.id} onPress={()=>setFindingEngagement(x.id)}/>)}</View><Label text="Category"/><View style={s.wrap}>{['Control Weakness','Reconciliation Exception','Compliance Breach','Unauthorized Transaction','Documentation Gap','Segregation of Duties','Fraud Indicator','Reporting Error'].map(x=><Choice key={x} label={x} selected={findingCategory===x} onPress={()=>setFindingCategory(x)}/>)}</View><Label text="Risk"/><View style={s.wrap}>{RISK_LEVELS.map(x=><Choice key={x} label={x} selected={findingRisk===x} onPress={()=>setFindingRisk(x)}/>)}</View>{[['Finding title',findingTitle,setFindingTitle],['Condition / what was found',findingCondition,setFindingCondition],['Criteria / expected control',findingCriteria,setFindingCriteria],['Cause',findingCause,setFindingCause],['Effect / risk exposure',findingEffect,setFindingEffect],['Recommendation',findingRecommendation,setFindingRecommendation]].map((a:any)=><TextInput key={a[0]} style={s.input} placeholder={a[0]} value={a[1]} onChangeText={a[2]} multiline/>)}<Pressable disabled={!!busy||!findingEngagement||!findingTitle.trim()||!findingCondition.trim()||!findingRecommendation.trim()} style={[s.primary,(!!busy||!findingEngagement||!findingTitle.trim()||!findingCondition.trim()||!findingRecommendation.trim())&&s.disabled]} onPress={()=>run('finding',createFinding)}><Text style={s.white}>{busy==='finding'?'Saving…':'Record Finding'}</Text></Pressable></Drop>:null}
  <Drop title={`Findings & Recommendations (${findings.length})`} open={open==='findings'} onPress={()=>toggle('findings')}>{findings.map((x:any)=><View key={x.id} style={s.row}><Text style={s.rowTitle}>{x.finding_reference} · {x.title}</Text><Text>{x.risk_rating} Risk · {x.status}</Text><Text style={s.meta}>{x.recommendation}</Text></View>)}{!findings.length?<Text>No audit findings recorded.</Text>:null}</Drop>
  {cap.respond&&findings.some((x:any)=>!['Closed','Accepted Risk'].includes(x.status))?<Drop title="Management Response" open={open==='response'} onPress={()=>toggle('response')}><View style={s.wrap}>{findings.filter((x:any)=>!['Closed','Accepted Risk'].includes(x.status)).map((x:any)=><Choice key={x.id} label={x.finding_reference} selected={responseFinding===x.id} onPress={()=>setResponseFinding(x.id)}/>)}</View><TextInput style={s.input} placeholder="Management response" value={responseText} onChangeText={setResponseText} multiline/><TextInput style={s.input} placeholder="Corrective action" value={correctiveAction} onChangeText={setCorrectiveAction} multiline/><TextInput style={s.input} placeholder="Due date YYYY-MM-DD" value={dueDate} onChangeText={setDueDate}/><Pressable disabled={!!busy||!responseFinding||!responseText.trim()||!correctiveAction.trim()} style={[s.primary,(!!busy||!responseFinding||!responseText.trim()||!correctiveAction.trim())&&s.disabled]} onPress={()=>run('response',submitResponse)}><Text style={s.white}>{busy==='response'?'Submitting…':'Submit Response'}</Text></Pressable></Drop>:null}
  <Drop title={`Corrective Actions (${actions.length})`} open={open==='actions'} onPress={()=>toggle('actions')}>{actions.map((x:any)=><View key={x.id} style={s.row}><Text style={s.rowTitle}>{x.action_text}</Text><Text>{x.status} · Due {x.due_date||'Not set'}</Text>{cap.followup&&!['Verified','Closed'].includes(x.status)?<View style={s.actions}><Pressable disabled={!!busy} style={[s.mini,!!busy&&s.disabled]} onPress={()=>run(x.id,()=>verifyFinanceInternalAuditAction(x.id,'Verified','Follow-up evidence verified'))}><Text style={s.white}>Verify & Close</Text></Pressable><Pressable disabled={!!busy} style={[s.secondary,!!busy&&s.disabled]} onPress={()=>run(x.id,()=>verifyFinanceInternalAuditAction(x.id,'Reopen','Further action required'))}><Text>Reopen</Text></Pressable></View>:null}</View>)}{!actions.length?<Text>No corrective actions recorded.</Text>:null}</Drop>
  <Drop title="Governance & Independence" open={open==='governance'} onPress={()=>toggle('governance')}><Text style={s.note}>Internal Auditor can open and read Finance source records and attach evidence without changing accounting records. Finance management responds to findings but cannot erase evidence or self-close findings. CEO/Manager retain oversight; External Auditor remains controlled read-only.</Text></Drop>
  {msg?<Text style={s.err}>{msg}</Text>:null}
 </View>
}
function ReadOnlyFile({data,onClose}:{data:any;onClose:()=>void}){const record=data?.record||{};const keys=Object.keys(record).filter(k=>!['id','created_by','updated_by'].includes(k));return <View style={s.file}><View style={s.fileHead}><View style={{flex:1}}><Text style={s.fileTitle}>READ-ONLY AUDIT FILE</Text><Text style={s.good}>Verified source: {data?.category||'Finance'} · No editing permitted</Text></View><Pressable style={s.secondary} onPress={onClose}><Text>Close</Text></Pressable></View>{keys.map(k=><View key={k} style={s.field}><Text style={s.fieldLabel}>{k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}</Text><Text style={s.fieldValue}>{formatValue(record[k])}</Text></View>)}{data?.journal_lines?.length?<><Text style={s.subTitle}>Journal Lines</Text>{data.journal_lines.map((x:any,i:number)=><View key={i} style={s.row}><Text>{x.account_name||x.account_code||`Line ${i+1}`}</Text><Text style={s.meta}>Debit {Number(x.debit||0).toLocaleString()} · Credit {Number(x.credit||0).toLocaleString()}</Text></View>)}</>:null}{data?.supporting_document_path?<Text style={s.good}>Supporting document reference: {data.supporting_document_path}</Text>:null}</View>}
function formatValue(v:any){if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='object')return JSON.stringify(v);return String(v)}
function Drop({title,open,onPress,children}:{title:string;open:boolean;onPress:()=>void;children:any}){return <View style={s.drop}><Pressable style={s.dropHead} onPress={onPress}><Text style={s.dropTitle}>{title}</Text><Text style={s.arrow}>{open?'▲':'▼'}</Text></Pressable>{open?<View style={s.dropBody}>{children}</View>:null}</View>}
function Metric({n,label}:{n:number;label:string}){return <View style={s.metric}><Text style={s.num}>{typeof n==='number'&&Math.abs(n)>=1000?n.toLocaleString():n}</Text><Text style={s.meta}>{label}</Text></View>}
function Label({text}:{text:string}){return <Text style={s.label}>{text}</Text>}
function Choice({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,selected&&s.choiceSelected]}><Text style={[s.choiceText,selected&&s.choiceTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
const s=StyleSheet.create({box:{borderTopWidth:1,borderTopColor:'#e5e7eb',marginTop:14,paddingTop:14},h:{fontWeight:'900',fontSize:18,color:'#14213d'},note:{fontSize:12,color:'#64748b',lineHeight:18,marginTop:5},metrics:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},metric:{width:'47%',backgroundColor:'#eef6f3',padding:11,borderRadius:12},num:{fontWeight:'900',fontSize:19,color:'#08745a'},meta:{fontSize:12,color:'#64748b'},drop:{borderTopWidth:1,borderTopColor:'#e5e7eb',marginTop:10},dropHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:14},dropTitle:{fontWeight:'900',fontSize:16,color:'#14213d',flex:1},arrow:{fontWeight:'900',color:'#08745a',paddingLeft:10},dropBody:{paddingBottom:12},wrap:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:7},tag:{backgroundColor:'#eef2f7',paddingVertical:7,paddingHorizontal:9,borderRadius:9},tagText:{fontSize:12,color:'#334155'},label:{fontWeight:'800',fontSize:13,color:'#334155',marginTop:10,marginBottom:3},choice:{borderWidth:1,borderColor:'#cbd5e1',backgroundColor:'#fff',borderRadius:9,paddingVertical:8,paddingHorizontal:9},choiceSelected:{borderColor:'#0b5d45',backgroundColor:'#dff1eb'},choiceText:{fontSize:12,color:'#334155'},choiceTextSelected:{fontWeight:'900',color:'#0b5d45'},input:{borderWidth:1,borderColor:'#cbd5e1',backgroundColor:'#fff',borderRadius:9,padding:10,marginTop:8},primary:{backgroundColor:'#0b5d45',padding:10,borderRadius:9,alignSelf:'flex-start',marginTop:9},mini:{backgroundColor:'#0b5d45',padding:8,borderRadius:8,alignSelf:'flex-start',marginTop:6},read:{backgroundColor:'#14213d',padding:8,borderRadius:8,alignSelf:'flex-start',marginTop:6},secondary:{backgroundColor:'#e2e8f0',padding:8,borderRadius:8,marginTop:6},white:{color:'#fff',fontWeight:'800'},disabled:{opacity:.5},row:{borderTopWidth:1,borderTopColor:'#e5e7eb',paddingVertical:10,gap:4},selectedRow:{backgroundColor:'#f0f8f5'},rowTitle:{fontWeight:'900'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},err:{color:'#9b1c1c',marginTop:8},count:{fontWeight:'800',marginTop:10,color:'#334155'},subTitle:{fontWeight:'900',fontSize:15,color:'#14213d',marginTop:14},good:{fontSize:12,color:'#08745a',fontWeight:'800'},warn:{fontSize:12,color:'#9a3412',backgroundColor:'#fff7ed',padding:9,borderRadius:8,marginTop:7},file:{borderWidth:1,borderColor:'#94a3b8',backgroundColor:'#f8fafc',borderRadius:12,padding:12,marginTop:12},fileHead:{flexDirection:'row',alignItems:'flex-start',gap:8},fileTitle:{fontWeight:'900',fontSize:15,color:'#14213d'},field:{borderTopWidth:1,borderTopColor:'#e2e8f0',paddingVertical:8,marginTop:5},fieldLabel:{fontSize:11,fontWeight:'900',color:'#64748b'},fieldValue:{fontSize:13,color:'#0f172a',marginTop:3}});
