import React,{useEffect,useMemo,useState}from'react';
import{Alert,Image,Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import*as ImagePicker from'expo-image-picker';import{supabase}from'./src/supabase';

type Service={id:string;name:string;category:string|null;price:number|null};
type Client={id:string;client_number:string;full_name:string;phone:string|null;whatsapp_number:string|null;address:string|null;photo_path:string|null;first_seen_at?:string|null;last_seen_at?:string|null};
type Visit={id:string;visit_number:string;client_id:string;service_name_snapshot:string;service_category_snapshot:string|null;service_location:string;amount_paid:number;payment_method:string|null;payment_reference:string|null;completed_at:string|null;departed_at:string|null;created_at:string};
type Expense={id:string;expense_number:string;expense_date:string;category:string;description:string;amount:number;payment_method:string|null;payment_reference:string|null;supplier_payee:string|null;notes:string|null;created_at:string};
type FinanceRow={period:string;income:number;expenses:number;net:number;service_count:number;expense_count:number};
type Tab='DASHBOARD'|'CUSTOMERS'|'SERVICE'|'EXPENSES'|'REPORTS';
const money=(n:any)=>`TZS ${Number(n||0).toLocaleString()}`;
const today=()=>new Date().toISOString().slice(0,10);
const month=()=>today().slice(0,7)+'-01';
const year=()=>today().slice(0,4)+'-01-01';

export default function App(){
 const[session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[tab,setTab]=useState<Tab>('DASHBOARD'),[busy,setBusy]=useState(false),[services,setServices]=useState<Service[]>([]),[clients,setClients]=useState<Client[]>([]),[visits,setVisits]=useState<Visit[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[daily,setDaily]=useState<FinanceRow|null>(null),[monthly,setMonthly]=useState<FinanceRow|null>(null),[yearly,setYearly]=useState<FinanceRow|null>(null),[selected,setSelected]=useState<Client|null>(null),[history,setHistory]=useState<Visit[]>([]),[query,setQuery]=useState('');
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[wa,setWa]=useState(''),[address,setAddress]=useState(''),[photo,setPhoto]=useState<string|null>(null),[service,setService]=useState<Service|null>(null),[amount,setAmount]=useState(''),[location,setLocation]=useState('OFFICE'),[paymentMethod,setPaymentMethod]=useState('CASH'),[paymentRef,setPaymentRef]=useState(''),[serviceNotes,setServiceNotes]=useState('');
 const[expDate,setExpDate]=useState(today()),[expCategory,setExpCategory]=useState('Office Expenses'),[expDescription,setExpDescription]=useState(''),[expAmount,setExpAmount]=useState(''),[expMethod,setExpMethod]=useState('CASH'),[expRef,setExpRef]=useState(''),[expPayee,setExpPayee]=useState(''),[expNotes,setExpNotes]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{x}={x:supabase.auth.onAuthStateChange((_e,s)=>setSession(s))};return()=>x.data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)refreshAll()},[session]);
 async function refreshAll(){setBusy(true);try{const[d,m,y,s,c,v,e]=await Promise.all([
   supabase.from('crm_finance_daily').select('*').eq('period',today()).maybeSingle(),supabase.from('crm_finance_monthly').select('*').eq('period',month()).maybeSingle(),supabase.from('crm_finance_yearly').select('*').eq('period',year()).maybeSingle(),supabase.from('services').select('id,name,category,price').eq('is_active',true).order('category').order('name'),supabase.from('crm_clients').select('id,client_number,full_name,phone,whatsapp_number,address,photo_path,first_seen_at,last_seen_at').order('last_seen_at',{ascending:false}).limit(500),supabase.from('crm_client_visits').select('id,visit_number,client_id,service_name_snapshot,service_category_snapshot,service_location,amount_paid,payment_method,payment_reference,completed_at,departed_at,created_at').order('created_at',{ascending:false}).limit(300),supabase.from('crm_expenses').select('id,expense_number,expense_date,category,description,amount,payment_method,payment_reference,supplier_payee,notes,created_at').order('expense_date',{ascending:false}).order('created_at',{ascending:false}).limit(300)
  ]);for(const r of[d,m,y,s,c,v,e])if(r.error)throw r.error;setDaily((d.data||zero(today()))as FinanceRow);setMonthly((m.data||zero(month()))as FinanceRow);setYearly((y.data||zero(year()))as FinanceRow);setServices((s.data||[])as Service[]);setClients((c.data||[])as Client[]);setVisits((v.data||[])as Visit[]);setExpenses((e.data||[])as Expense[])}catch(err:any){Alert.alert('Could not load database',err.message||String(err))}finally{setBusy(false)}}
 async function login(){setBusy(true);const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(error)Alert.alert('Login failed',error.message)}
 async function pickPhoto(camera:boolean){const p=camera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!p.granted)return Alert.alert('Permission required','Camera/photo permission is required.');const r=camera?await ImagePicker.launchCameraAsync({quality:.75}):await ImagePicker.launchImageLibraryAsync({quality:.75});if(!r.canceled)setPhoto(r.assets[0].uri)}
 async function uploadClientPhoto(clientId:string){if(!photo)return null;const b=await(await fetch(photo)).blob(),path=`${clientId}/${Date.now()}.jpg`;const{error}=await supabase.storage.from('crm-client-photos').upload(path,b,{contentType:'image/jpeg',upsert:false});if(error)throw error;return path}
 async function saveService(){if(!name.trim()&&!selected)return Alert.alert('Required','Enter or select customer.');if(!service)return Alert.alert('Required','Select a NEBRIN service.');const paid=Number(amount||0);if(!Number.isFinite(paid)||paid<0)return Alert.alert('Invalid amount','Enter a valid amount paid.');setBusy(true);try{let c=selected;if(!c){const{data,error}=await supabase.from('crm_clients').insert({full_name:name.trim(),phone:phone.trim()||null,whatsapp_number:wa.trim()||null,address:address.trim()||null}).select().single();if(error)throw error;c=data as Client}else{const{error}=await supabase.from('crm_clients').update({full_name:name.trim()||c.full_name,phone:phone.trim()||null,whatsapp_number:wa.trim()||null,address:address.trim()||null,last_seen_at:new Date().toISOString()}).eq('id',c.id);if(error)throw error}const pp=await uploadClientPhoto(c.id);if(pp){const{error}=await supabase.from('crm_clients').update({photo_path:pp}).eq('id',c.id);if(error)throw error}const{error}=await supabase.from('crm_client_visits').insert({client_id:c.id,service_id:service.id,service_name_snapshot:service.name,service_category_snapshot:service.category,service_location:location,amount_charged:paid,amount_paid:paid,payment_method:paymentMethod,payment_reference:paymentRef.trim()||null,status:'COMPLETED',notes:serviceNotes.trim()||null,completed_at:new Date().toISOString(),departed_at:new Date().toISOString()});if(error)throw error;Alert.alert('Saved','Customer service saved. Income dashboard has been updated automatically.');resetService();setTab('DASHBOARD');await refreshAll()}catch(err:any){Alert.alert('Could not save',err.message||String(err))}finally{setBusy(false)}}
 async function saveExpense(){const n=Number(expAmount);if(!expDescription.trim()||!Number.isFinite(n)||n<=0)return Alert.alert('Required','Enter expense description and a valid amount.');setBusy(true);try{const{error}=await supabase.from('crm_expenses').insert({expense_date:expDate,category:expCategory,description:expDescription.trim(),amount:n,payment_method:expMethod,payment_reference:expRef.trim()||null,supplier_payee:expPayee.trim()||null,notes:expNotes.trim()||null,recorded_by:session.user.id});if(error)throw error;Alert.alert('Expense saved','Daily, monthly and yearly income/expense totals have been recalculated automatically.');setExpDescription('');setExpAmount('');setExpRef('');setExpPayee('');setExpNotes('');setTab('DASHBOARD');await refreshAll()}catch(err:any){Alert.alert('Could not save expense',err.message||String(err))}finally{setBusy(false)}}
 async function chooseClient(c:Client){setSelected(c);setName(c.full_name);setPhone(c.phone||'');setWa(c.whatsapp_number||'');setAddress(c.address||'');const{data,error}=await supabase.from('crm_client_visits').select('id,visit_number,client_id,service_name_snapshot,service_category_snapshot,service_location,amount_paid,payment_method,payment_reference,completed_at,departed_at,created_at').eq('client_id',c.id).order('created_at',{ascending:false}).limit(50);if(!error)setHistory((data||[])as Visit[])}
 function resetService(){setSelected(null);setHistory([]);setName('');setPhone('');setWa('');setAddress('');setPhoto(null);setService(null);setAmount('');setPaymentRef('');setServiceNotes('')}
 const shown=useMemo(()=>clients.filter(c=>(c.full_name+' '+(c.phone||'')+' '+(c.whatsapp_number||'')+' '+c.client_number+' '+(c.address||'')).toLowerCase().includes(query.toLowerCase())),[clients,query]);
 const topServices=useMemo(()=>{const m=new Map<string,{name:string,count:number,total:number}>();for(const v of visits){const k=v.service_name_snapshot||'Unknown';const x=m.get(k)||{name:k,count:0,total:0};x.count++;x.total+=Number(v.amount_paid||0);m.set(k,x)}return [...m.values()].sort((a,b)=>b.total-a.total).slice(0,8)},[visits]);
 if(!session)return <SafeAreaView style={s.page}><View style={s.login}><Text style={s.brand}>NEBRIN ONLINE SERVICE COMPANY LIMITED</Text><Text style={s.h1}>Client & Finance Database</Text><Text style={s.muted}>Authorized staff access only</Text><Input v={email} set={setEmail} ph="Staff email"/><Input v={password} set={setPassword} ph="Password" secure/><Button t={busy?'Signing in…':'Sign In'} f={login}/></View></SafeAreaView>;
 return <SafeAreaView style={s.page}><View style={{flex:1}}><ScrollView contentContainerStyle={s.body}><View style={s.top}><View style={{flex:1}}><Text style={s.brand}>NEBRIN CLIENT DATABASE</Text><Text style={s.h1}>Customers • Services • Finance</Text><Text style={s.muted}>Income is created from completed customer services. Expenses are entered separately.</Text></View><Pressable onPress={()=>supabase.auth.signOut()}><Text style={s.out}>Sign out</Text></Pressable></View><View style={s.nav}>{(['DASHBOARD','CUSTOMERS','SERVICE','EXPENSES','REPORTS']as Tab[]).map(t=><Pressable key={t} onPress={()=>setTab(t)} style={[s.navBtn,tab===t&&s.navOn]}><Text style={tab===t?s.navTextOn:s.navText}>{t==='SERVICE'?'NEW SERVICE':t}</Text></Pressable>)}</View>
 {tab==='DASHBOARD'?<><Card title="Automatic Financial Dashboard"><Text style={s.muted}>Every completed customer service adds to income automatically. Every saved expense adds to matumizi automatically.</Text><Period title="TODAY" r={daily}/><Period title="THIS MONTH" r={monthly}/><Period title="THIS YEAR" r={yearly}/><Button t={busy?'Refreshing…':'Refresh Totals'} f={refreshAll}/></Card><View style={s.grid}><Mini n={clients.length} label="Customers loaded"/><Mini n={visits.length} label="Recent service records"/><Mini n={services.length} label="Active NEBRIN services"/><Mini n={expenses.length} label="Expense records loaded"/></View><Card title="Recent Customer Income">{visits.slice(0,10).map(v=><View key={v.id} style={s.row}><Text style={s.bold}>{v.service_name_snapshot}</Text><Text style={s.muted}>{v.visit_number} · {v.service_location} · {money(v.amount_paid)}</Text></View>)}{!visits.length?<Text style={s.muted}>No service income recorded yet.</Text>:null}</Card></>:null}
 {tab==='CUSTOMERS'?<><Card title="Customer Database"><Input v={query} set={setQuery} ph="Search name, phone, WhatsApp, area or client number"/><Text style={s.muted}>{shown.length} matching customers</Text>{shown.slice(0,60).map(c=><Pressable key={c.id} style={s.row} onPress={()=>chooseClient(c)}><Text style={s.bold}>{c.full_name}</Text><Text style={s.muted}>{c.client_number} · {c.phone||'No phone'} · WhatsApp: {c.whatsapp_number||'—'}</Text><Text style={s.muted}>{c.address||'Area not recorded'}</Text></Pressable>)}</Card>{selected?<Card title={`Customer Profile — ${selected.client_number}`}><Text style={s.profile}>{selected.full_name}</Text><Text>Phone: {selected.phone||'—'}</Text><Text>WhatsApp: {selected.whatsapp_number||'—'}</Text><Text>From/Area: {selected.address||'—'}</Text>{selected.whatsapp_number?<Button t="Open WhatsApp" f={()=>Linking.openURL(`https://wa.me/${selected.whatsapp_number!.replace(/\D/g,'')}`)}/>:null}<Text style={s.h3}>Service History</Text>{history.map(v=><View key={v.id} style={s.row}><Text style={s.bold}>{v.service_name_snapshot}</Text><Text style={s.muted}>{v.visit_number} · {money(v.amount_paid)} · {v.service_location}</Text><Text style={s.muted}>Completed: {(v.completed_at||v.created_at).slice(0,16).replace('T',' ')}</Text></View>)}{!history.length?<Text style={s.muted}>No service history found.</Text>:null}</Card>:null}</>:null}
 {tab==='SERVICE'?<><Card title="Find or Register Customer"><Input v={query} set={setQuery} ph="Search existing customer"/>{query?shown.slice(0,7).map(c=><Pressable key={c.id} style={s.row} onPress={()=>chooseClient(c)}><Text style={s.bold}>{c.full_name}</Text><Text style={s.muted}>{c.client_number} · {c.phone||c.whatsapp_number||'No phone'}</Text></Pressable>):null}<Button t="Clear / New Customer" f={resetService} secondary/></Card><Card title={selected?`Existing Customer — ${selected.client_number}`:'New Customer Details'}><Input v={name} set={setName} ph="Full name"/><Input v={phone} set={setPhone} ph="Phone number"/><Input v={wa} set={setWa} ph="WhatsApp number"/><Input v={address} set={setAddress} ph="Area / address / where customer comes from"/><Text style={s.label}>Customer reference photo</Text>{photo?<Image source={{uri:photo}} style={s.photo}/>:null}<View style={s.buttons}><Button t="Take Photo" f={()=>pickPhoto(true)}/><Button t="Choose Photo" f={()=>pickPhoto(false)} secondary/></View></Card><Card title="Service & Payment"><Text style={s.label}>Select NEBRIN service</Text><View style={s.chips}>{services.map(x=><Pressable key={x.id} style={[s.chip,service?.id===x.id&&s.chipOn]} onPress={()=>{setService(x);if(x.price!=null)setAmount(String(x.price))}}><Text style={service?.id===x.id?s.chipTextOn:s.chipText}>{x.name}</Text><Text style={service?.id===x.id?s.chipTextOn:s.chipSmall}>{x.category||''}</Text></Pressable>)}</View><Text style={s.label}>Where service was provided</Text><Choice values={['OFFICE','ONLINE','FIELD','OTHER']} value={location} set={setLocation}/><Input v={amount} set={setAmount} ph="Amount paid (TZS)" keyboard="numeric"/><Text style={s.label}>Payment method</Text><Choice values={['CASH','M-PESA','AIRTEL MONEY','MIXX BY YAS','HALOPESA','BANK','OTHER']} value={paymentMethod} set={setPaymentMethod}/><Input v={paymentRef} set={setPaymentRef} ph="Payment/reference number (optional)"/><Input v={serviceNotes} set={setServiceNotes} ph="Service notes (optional)" multiline/><Button t={busy?'Saving…':'Save Customer Service'} f={saveService}/><Text style={s.note}>When saved as completed, amount paid becomes income automatically and appears in day/month/year reports.</Text></Card></>:null}
 {tab==='EXPENSES'?<><Card title="Record Company Expense"><Text style={s.muted}>Jaza matumizi hapa. Mfumo utapunguza matumizi kwenye mapato na kuonyesha salio/net automatically.</Text><Input v={expDate} set={setExpDate} ph="Expense date YYYY-MM-DD"/><Text style={s.label}>Expense category</Text><Choice values={['Office Expenses','Transport','Internet & Airtime','Electricity','Rent','Stationery','Salary/Wages','Marketing','Equipment','Government Fees','Maintenance','Other']} value={expCategory} set={setExpCategory}/><Input v={expDescription} set={setExpDescription} ph="Expense description"/><Input v={expAmount} set={setExpAmount} ph="Amount (TZS)" keyboard="numeric"/><Text style={s.label}>Payment method</Text><Choice values={['CASH','M-PESA','AIRTEL MONEY','MIXX BY YAS','HALOPESA','BANK','OTHER']} value={expMethod} set={setExpMethod}/><Input v={expPayee} set={setExpPayee} ph="Paid to / supplier"/><Input v={expRef} set={setExpRef} ph="Receipt/payment reference"/><Input v={expNotes} set={setExpNotes} ph="Notes (optional)" multiline/><Button t={busy?'Saving…':'Save Expense'} f={saveExpense}/></Card><Card title="Recent Expenses">{expenses.slice(0,30).map(e=><View key={e.id} style={s.row}><Text style={s.bold}>{e.description}</Text><Text style={s.muted}>{e.expense_number} · {e.expense_date} · {money(e.amount)}</Text><Text style={s.muted}>{e.category}{e.supplier_payee?` · ${e.supplier_payee}`:''}</Text></View>)}{!expenses.length?<Text style={s.muted}>No expenses recorded yet.</Text>:null}</Card></>:null}
 {tab==='REPORTS'?<><Card title="Income & Expense Summary"><Period title="TODAY" r={daily}/><Period title="THIS MONTH" r={monthly}/><Period title="THIS YEAR" r={yearly}/></Card><Card title="Top Services by Recorded Income">{topServices.map(x=><View key={x.name} style={s.row}><Text style={s.bold}>{x.name}</Text><Text style={s.muted}>{x.count} records · {money(x.total)}</Text></View>)}</Card><Card title="Service Catalogue"><Text style={s.muted}>{services.length} active NEBRIN services</Text>{services.map(x=><View key={x.id} style={s.row}><Text style={s.bold}>{x.name}</Text><Text style={s.muted}>{x.category||'Uncategorized'}{x.price!=null?` · Standard price ${money(x.price)}`:''}</Text></View>)}</Card></>:null}
 </ScrollView></View></SafeAreaView>}

function zero(period:string):FinanceRow{return{period,income:0,expenses:0,net:0,service_count:0,expense_count:0}}
function Period({title,r}:{title:string;r:FinanceRow|null}){const x=r||zero('');return <View style={s.period}><Text style={s.periodTitle}>{title}</Text><View style={s.grid}><MoneyBox label="Income / Mapato" value={x.income}/><MoneyBox label="Expenses / Matumizi" value={x.expenses}/><MoneyBox label="Net / Salio" value={x.net}/><Mini n={Number(x.service_count||0)} label="Services paid"/></View></View>}
function MoneyBox({label,value}:{label:string;value:number}){return <View style={s.metric}><Text style={s.metricMoney}>{money(value)}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Mini({n,label}:{n:number;label:string}){return <View style={s.metric}><Text style={s.metricNum}>{Number(n||0).toLocaleString()}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Choice({values,value,set}:{values:string[];value:string;set:(x:string)=>void}){return <View style={s.chips}>{values.map(x=><Pressable key={x} style={[s.choice,value===x&&s.chipOn]} onPress={()=>set(x)}><Text style={value===x?s.chipTextOn:s.chipText}>{x}</Text></Pressable>)}</View>}
function Input({v,set,ph,secure,keyboard,multiline}:{v:string;set:(x:string)=>void;ph:string;secure?:boolean;keyboard?:any;multiline?:boolean}){return <TextInput value={v} onChangeText={set} placeholder={ph} secureTextEntry={secure} keyboardType={keyboard} multiline={multiline} style={[s.input,multiline&&{minHeight:75,textAlignVertical:'top'}]}/>}function Button({t,f,secondary}:{t:string;f:()=>void;secondary?:boolean}){return <Pressable onPress={f} style={[s.btn,secondary&&s.btn2]}><Text style={[s.bt,secondary&&s.bt2]}>{t}</Text></Pressable>}function Card({title,children}:{title:string;children:any}){return <View style={s.card}><Text style={s.h2}>{title}</Text>{children}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f1f5f4'},body:{padding:16,paddingTop:42,paddingBottom:80},login:{margin:22,marginTop:110,padding:22,backgroundColor:'#fff',borderRadius:22},top:{flexDirection:'row',gap:12,alignItems:'flex-start',marginBottom:15},brand:{fontWeight:'900',color:'#08795b',letterSpacing:.4},h1:{fontSize:27,fontWeight:'900',color:'#12213c',marginTop:4},h2:{fontSize:21,fontWeight:'900',color:'#12213c',marginBottom:12},h3:{fontSize:18,fontWeight:'900',color:'#12213c',marginTop:18,marginBottom:6},profile:{fontSize:22,fontWeight:'900',color:'#12213c',marginBottom:8},muted:{color:'#69778c',fontSize:14,lineHeight:20},note:{color:'#496477',fontSize:12,marginTop:10,lineHeight:18},out:{color:'#8b1e1e',fontWeight:'800'},nav:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:15},navBtn:{paddingVertical:9,paddingHorizontal:11,borderRadius:12,backgroundColor:'#e3ebe8'},navOn:{backgroundColor:'#08795b'},navText:{fontSize:11,fontWeight:'800',color:'#334155'},navTextOn:{fontSize:11,fontWeight:'900',color:'#fff'},card:{backgroundColor:'#fff',borderRadius:20,padding:17,marginBottom:15},input:{borderWidth:1,borderColor:'#cad4dc',backgroundColor:'#fff',borderRadius:12,padding:12,fontSize:15,marginTop:9},label:{fontWeight:'800',color:'#24344d',marginTop:14,marginBottom:8},buttons:{flexDirection:'row',flexWrap:'wrap',gap:8},btn:{backgroundColor:'#08795b',paddingVertical:12,paddingHorizontal:16,borderRadius:11,marginTop:11,alignSelf:'flex-start'},btn2:{backgroundColor:'#e8f1ee'},bt:{color:'#fff',fontWeight:'900'},bt2:{color:'#08795b'},photo:{width:120,height:120,borderRadius:15},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#cbd5df',borderRadius:16,paddingVertical:8,paddingHorizontal:10,maxWidth:'100%'},choice:{borderWidth:1,borderColor:'#cbd5df',borderRadius:13,paddingVertical:8,paddingHorizontal:10},chipOn:{backgroundColor:'#08795b',borderColor:'#08795b'},chipText:{color:'#334155'},chipTextOn:{color:'#fff',fontWeight:'800'},chipSmall:{color:'#64748b',fontSize:10,marginTop:2},row:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#edf0f2'},bold:{fontWeight:'800',color:'#17233b'},grid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:10},metric:{width:'48%',backgroundColor:'#eef6f3',borderRadius:14,padding:12,minHeight:82},metricMoney:{fontSize:18,fontWeight:'900',color:'#08795b'},metricNum:{fontSize:24,fontWeight:'900',color:'#08795b'},metricLabel:{fontSize:12,color:'#64748b',marginTop:5},period:{marginTop:15,paddingTop:12,borderTopWidth:1,borderTopColor:'#e5e7eb'},periodTitle:{fontWeight:'900',color:'#12213c',marginBottom:8}});
