import{supabase}from'./supabase';import type{BootstrapPayload,CommandCentrePayload,DigitalOfficeStatus,FinanceGovernancePayload,FinancePayload,HRPayload,NotificationPayload,SecurityPayload,WorkflowPayload}from'../types/app';
export function errorMessage(e:unknown){return e instanceof Error?e.message:String((e as any)?.message||'Unexpected error')}
async function call<T>(name:string,body:Record<string,unknown>):Promise<T>{const{data,error}=await supabase.functions.invoke(name,{method:'POST',body});if(error)throw new Error(error.message);if(!data?.success)throw new Error(data?.error||`Unable to load ${name}.`);return data as T}
export const bootstrapApp=()=>call<BootstrapPayload>('nebrin-app-bootstrap',{});export const getDigitalOfficeStatus=()=>call<DigitalOfficeStatus>('nebrin-digital-office',{action:'status'});export const digitalOfficeAction=(action:'check_in'|'check_out'|'start_break'|'end_break')=>call<any>('nebrin-digital-office',{action});export const getCommandCentre=()=>call<CommandCentrePayload>('nebrin-command-centre',{});export const getHRCentre=()=>call<HRPayload>('nebrin-hr-centre',{action:'dashboard'});export const getWorkflowCentre=()=>call<WorkflowPayload>('nebrin-workflow-centre',{action:'overview'});export const secretaryRouteCase=(case_id:string,to_department_id:string,instruction?:string)=>call<any>('nebrin-workflow-centre',{action:'secretary_route',case_id,to_department_id,instruction:instruction||null});export const routeWorkflowFile=(file_id:string,to_department_id:string,instruction?:string)=>call<any>('nebrin-workflow-centre',{action:'route_file',file_id,to_department_id,instruction:instruction||null});export const claimWorkflowFile=(file_id:string)=>call<any>('nebrin-workflow-centre',{action:'claim_file',file_id});export const returnWorkflowFile=(file_id:string,note?:string)=>call<any>('nebrin-workflow-centre',{action:'return_file',file_id,note:note||'Returned after action'});export const completeWorkflowFile=(file_id:string,public_message?:string)=>call<any>('nebrin-workflow-centre',{action:'complete_file',file_id,public_message:public_message||'Your NEBRIN request has been completed.'});
export async function getFinanceCentre():Promise<FinancePayload>{const raw=await call<any>('nebrin-finance-centre',{action:'dashboard'});const d=raw.data||{};return{success:true,summary:{generated:Number(d.summary?.generated||0),paid:Number(d.summary?.paid||0),cancelled:Number(d.summary?.cancelled||0),expired:Number(d.summary?.expired||0)},payment_methods:Array.isArray(d.payment_methods)?d.payment_methods:[],payment_requests:Array.isArray(d.payment_requests)?d.payment_requests:[]}}
export const getFinanceGovernance=()=>call<FinanceGovernancePayload>('nebrin-finance-centre',{action:'governance'});export const decideFinanceAuditAccess=(access_id:string,decision:'Approved'|'Rejected',note?:string)=>call<any>('nebrin-finance-centre',{action:'audit_decision',access_id,decision,note:note||null});export const revokeFinanceAuditAccess=(access_id:string,note?:string)=>call<any>('nebrin-finance-centre',{action:'audit_revoke',access_id,note:note||null});
export const createCasePayment=(case_id:string,payment_method_id:string,amount:number)=>call<any>('nebrin-finance-centre',{action:'create_payment',case_id,payment_method_id,amount});export const recordPaymentCollection=(payment_request_id:string)=>call<any>('nebrin-finance-centre',{action:'record_collection',payment_request_id});export const verifyPayment=(payment_request_id:string)=>call<any>('nebrin-finance-centre',{action:'confirm_payment',payment_request_id});export const cancelPayment=(payment_request_id:string)=>call<any>('nebrin-finance-centre',{action:'cancel_payment',payment_request_id});
export const getNotificationCentre=()=>call<NotificationPayload>('nebrin-notification-centre',{action:'list'});export const markNotificationRead=(notification_id:string,source:'employee'|'department')=>call<any>('nebrin-notification-centre',{action:'mark_read',id:notification_id,source});export const markAllNotificationsRead=()=>call<any>('nebrin-notification-centre',{action:'mark_all_read'});
export const getSecurityCentre=()=>call<SecurityPayload>('nebrin-security-centre',{action:'overview'});export const decideApproval=(approval_id:string,decision:'Approved'|'Rejected',note?:string)=>call<any>('nebrin-security-centre',{action:'approval_decision',approval_id,decision,note:note||null});export const recordCEOAction=(incident_id:string,decision:string)=>call<any>('nebrin-security-centre',{action:'ceo_action',incident_id,decision});export const grantOvertime=(department:string)=>call<any>('nebrin-security-centre',{action:'grant_overtime',department});export const revokeOvertime=(department:string)=>call<any>('nebrin-security-centre',{action:'revoke_overtime',department});
